# GENERATED by scripts/gen_analysis.py from spec/analysis.v1.json — DO NOT EDIT.
"""A session analysis, server side. `extra="forbid"` plus the bounds below are the
enforcement half of analysis/schema.json: the constrained decoder that produced the
document honours enums and required fields, but string lengths and numeric ranges are
checked HERE, on the way into Postgres, or nowhere."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

ANALYSIS_VERSION = 1

Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]

#: Character caps by size class; the spec's `max` on a string field names one of these.
ANALYSIS_MAX_LENGTHS: dict[str, int] = {
    "headline": 90,
    "summary": 700,
    "short": 140,
    "medium": 300,
    "excerpt": 160,
}

#: Legal values for every enum, in spec order.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "outcome": ["shipped", "progressed", "explored", "blocked", "abandoned", "maintenance"],
    "feature_status": ["done", "partial", "started", "reverted"],
    "planning": ["none", "light", "explicit_plan", "plan_mode"],
    "iteration": ["linear", "iterative", "pivoted", "thrashing"],
    "steering": ["hands_off", "guided", "tight_loop", "micromanaged"],
    "verification": ["none", "manual_check", "ran_tests", "tests_added"],
    "scope_control": ["held", "expanded", "narrowed"],
    "archetype": ["architect", "velocity_machine", "quality_guardian", "night_owl", "explorer", "firefighter"],
    "friction_kind": ["misunderstanding", "tool_failure", "env_issue", "model_error", "scope_creep", "human_error", "waiting"],
    "tone": ["neutral", "terse", "polite", "frustrated", "mixed"],
    "work_kind": ["feature", "bugfix", "refactor", "infra", "docs", "test", "research", "ops"],
    "dimension": ["steering", "execution", "engineering", "product_instinct", "planning"],
}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "Feature": {"status": "feature_status"},
    "BuildStyle": {"planning": "planning", "iteration": "iteration", "steering": "steering", "verification": "verification", "scope_control": "scope_control"},
    "DimensionScore": {"dimension": "dimension"},
    "DecisionPattern": {},
    "Pivot": {},
    "Friction": {"kind": "friction_kind"},
    "Prompting": {"tone": "tone"},
    "SessionAnalysis": {"outcome": "outcome", "archetype": "archetype"},
}

#: model name -> map field name -> enum its keys must come from.
MAP_KEY_ENUMS: dict[str, dict[str, str]] = {
    "SessionAnalysis": {"work_mix": "work_kind"},
}


class Feature(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(max_length=140)
    status: str
    detail: str | None = Field(default=None, max_length=300)
    evidence: list[int] = Field(max_length=6)

    @field_validator("status")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class BuildStyle(BaseModel):
    model_config = ConfigDict(extra="forbid")

    planning: str
    iteration: str
    steering: str
    verification: str
    scope_control: str
    architecture_note: str | None = Field(default=None, max_length=300)

    @field_validator("planning", "iteration", "steering", "verification", "scope_control")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DimensionScore(BaseModel):
    model_config = ConfigDict(extra="forbid")

    dimension: str
    score: int = Field(ge=0, le=100)
    rationale: str = Field(max_length=140)

    @field_validator("dimension")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DecisionPattern(BaseModel):
    model_config = ConfigDict(extra="forbid")

    pattern: str = Field(max_length=140)
    prompt_excerpt: str = Field(max_length=160)
    effect: str | None = Field(default=None, max_length=140)


class Pivot(BaseModel):
    model_config = ConfigDict(extra="forbid")

    at_minute: int
    from_goal: str = Field(max_length=140)
    to_goal: str = Field(max_length=140)
    trigger: str | None = Field(default=None, max_length=140)


class Friction(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    description: str = Field(max_length=140)
    cost_minutes: int | None = None

    @field_validator("kind")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class Prompting(BaseModel):
    model_config = ConfigDict(extra="forbid")

    tone: str
    specificity: int = Field(ge=0, le=100)
    correction_share: float = Field(ge=0.0, le=1.0)
    question_share: float = Field(ge=0.0, le=1.0)
    note: str | None = Field(default=None, max_length=300)

    @field_validator("tone")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class SessionAnalysis(BaseModel):
    model_config = ConfigDict(extra="forbid")

    analysis_version: int
    model: str
    generated_at: datetime
    digest_hash: Sha256Hex
    digest_coverage: float = Field(ge=0.0, le=1.0)
    headline: str = Field(max_length=90)
    summary: str = Field(max_length=700)
    outcome: str
    features: list[Feature] = Field(max_length=8)
    work_mix: dict[str, Annotated[float, Field(ge=0.0, le=1.0)]]
    build_style: BuildStyle
    dimensions: list[DimensionScore] = Field(max_length=5)
    archetype: str | None = None
    decision_patterns: list[DecisionPattern] = Field(max_length=5)
    pivots: list[Pivot] = Field(max_length=5)
    friction: list[Friction] = Field(max_length=6)
    prompting: Prompting
    growth_edge: list[Annotated[str, Field(max_length=300)]] = Field(max_length=3)
    tags: list[Annotated[str, Field(max_length=140)]] = Field(max_length=8)
    confidence: float = Field(ge=0.0, le=1.0)
    contains_sensitive: bool

    @field_validator("outcome", "archetype")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v

    @field_validator("work_mix")
    @classmethod
    def _validate_map_keys(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[MAP_KEY_ENUMS[cls.__name__][info.field_name]]
        bad = sorted(k for k in v if k not in allowed)
        if bad:
            raise ValueError(
                '%s has keys %r not in %r' % (info.field_name, bad, allowed)
            )
        return v

