# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT.
"""The wire contract, server side. `extra="forbid"` is the belt-and-suspenders half of
the guarantee: even a hostile or stale client cannot push an undeclared field into
Postgres. The client-side half is that undeclared fields are unrepresentable at all."""

from __future__ import annotations

import re
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

CONTRACT_VERSION = 1

_SHA256 = re.compile(r"^[0-9a-f]{64}$")
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]

PUBLIC_FIELDS = [
    "abandoned_branch_tokens",
    "active_calc_version",
    "active_seconds",
    "agent_line_bucket",
    "agent_observed_at",
    "attrib_confidence",
    "card_png_url",
    "client_clock_offset_ms",
    "client_session_id",
    "client_version",
    "commit_count",
    "commit_deletions",
    "commit_insertions",
    "content_hash",
    "ended_at",
    "files_created",
    "files_touched",
    "harness",
    "human_edit_events",
    "human_prompt_count",
    "idle_seconds",
    "lines_added_agent",
    "lines_removed_agent",
    "machine_id",
    "model_state",
    "models",
    "notable",
    "prompt_count_basis",
    "repo_hash",
    "repo_id_basis",
    "repo_name",
    "repo_pepper_version",
    "sessionizer_version",
    "started_at",
    "state",
    "strip_columns",
    "strip_marks",
    "time_quality",
    "timeline_fidelity",
    "title",
    "title_source",
    "token_coverage",
    "token_dedupe",
    "token_scope",
    "tokens",
    "tokens_reported",
    "tool_calls",
    "tz_offset_minutes",
    "visible"
]

ANONYMOUS_FIELDS = [
    "abandoned_branch_tokens",
    "active_calc_version",
    "active_seconds",
    "agent_line_bucket",
    "agent_observed_at",
    "attrib_confidence",
    "card_png_url",
    "client_clock_offset_ms",
    "client_session_id",
    "client_version",
    "commit_count",
    "commit_deletions",
    "commit_insertions",
    "content_hash",
    "ended_at",
    "files_created",
    "files_touched",
    "harness",
    "human_edit_events",
    "human_prompt_count",
    "idle_seconds",
    "lines_added_agent",
    "lines_removed_agent",
    "machine_id",
    "model_state",
    "models",
    "notable",
    "prompt_count_basis",
    "repo_hash",
    "repo_id_basis",
    "repo_pepper_version",
    "sessionizer_version",
    "started_at",
    "state",
    "strip_columns",
    "strip_marks",
    "time_quality",
    "timeline_fidelity",
    "token_coverage",
    "token_dedupe",
    "token_scope",
    "tokens",
    "tokens_reported",
    "tool_calls",
    "tz_offset_minutes",
    "visible"
]

#: Legal values for every enum-typed field, so a client typo is a 422 with a useful
#: message rather than a constraint violation deep in a batch insert.
ENUM_VALUES: dict[str, list[str]] = {
    "harness": ["claude_code", "codex", "cursor_agent", "cursor_ide"],
    "time_quality": ["mtime_corrected", "ok"],
    "state": ["final"],
    "timeline_fidelity": ["coarse", "full", "header_only"],
    "prompt_count_basis": ["typed_promptsource", "user_bubble"],
    "agent_line_bucket": ["about_half", "almost_all_agent", "mostly_you", "nine_in_ten", "three_in_four", "unknown"],
    "attrib_confidence": ["high", "low", "medium", "none"],
    "token_dedupe": ["message_id", "none", "request_id"],
    "token_scope": ["mixed", "parent_aggregated"],
    "token_coverage": ["complete", "partial", "structurally_absent"],
    "model_state": ["known", "partial", "unknown"],
    "repo_id_basis": ["origin", "root_commit"],
    "title_source": ["harness", "template"],
}


class StripMarkWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ms: int
    k: int


class TokenBucketsWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    input: int
    output: int
    cache_read: int
    cache_w5m: int
    cache_w1h: int


class ModelShareWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    model_id: str
    output_token_share: float


class SessionUpload(BaseModel):
    model_config = ConfigDict(extra="forbid")

    client_session_id: Sha256Hex
    machine_id: Sha256Hex
    content_hash: Sha256Hex
    client_version: str
    sessionizer_version: int
    active_calc_version: int
    harness: str
    agent_observed_at: datetime
    client_clock_offset_ms: int
    started_at: datetime
    ended_at: datetime
    active_seconds: int
    idle_seconds: int
    tz_offset_minutes: int
    time_quality: str
    state: str
    visible: bool
    notable: bool
    strip_columns: str
    strip_marks: list[StripMarkWire]
    timeline_fidelity: str
    human_prompt_count: int
    prompt_count_basis: str
    tool_calls: dict[str, int]
    files_touched: int
    files_created: int
    lines_added_agent: int
    lines_removed_agent: int
    commit_count: int
    commit_insertions: int
    commit_deletions: int
    human_edit_events: int
    agent_line_bucket: str
    attrib_confidence: str
    tokens_reported: bool
    tokens: TokenBucketsWire | None = None
    abandoned_branch_tokens: int
    token_dedupe: str
    token_scope: str
    token_coverage: str
    models: list[ModelShareWire]
    model_state: str
    repo_hash: Sha256Hex | None = None
    repo_pepper_version: int
    repo_id_basis: str
    repo_name: str | None = None
    title: str | None = None
    title_source: str | None = None
    card_png_url: str | None = None

    @field_validator("harness", "time_quality", "state", "timeline_fidelity", "prompt_count_basis", "agent_line_bucket", "attrib_confidence", "token_dedupe", "token_scope", "token_coverage", "model_state", "repo_id_basis", "title_source")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ENUM_VALUES.get(info.field_name)
        if v is not None and allowed is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v

