# GENERATED by scripts/gen_narrative.py from spec/narrative.v1.json — DO NOT EDIT.
"""The builder narrative, server side.

`extra="forbid"` and the bounds below are the enforcement half of
analysis/narrative_schema.json. The constrained decoder that produced the document
honours `required` and `additionalProperties`, but string lengths are checked HERE, on
the way into Postgres, or nowhere.

The server does NOT write this document and cannot: it rests on prompt text, which never
leaves the machine (privacy/upload-contract.json). It validates it and stores it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

NARRATIVE_VERSION = 1

#: Character caps by size class; the spec's `max` on a string field names one of these.
NARRATIVE_MAX_LENGTHS: dict[str, int] = {
    "line": 220,
    "para": 400,
    "claim": 160,
    "experiment": 260,
    "model": 80,
}

#: Written by the runner after the model has spoken, never by the model itself.
STAMPED_FIELDS: list[str] = [
    "narrative_version",
    "model",
    "generated_at",
    "dashes_rewritten",
    "invented_numbers_dropped",
]


class NarrativeClaim(BaseModel):
    model_config = ConfigDict(extra="forbid")

    text: str = Field(max_length=160)
    evidence: str = Field(max_length=160)


class BuilderNarrative(BaseModel):
    model_config = ConfigDict(extra="forbid")

    archetype_line: str = Field(max_length=220)
    how_you_work: list[Annotated[str, Field(max_length=400)]] = Field(max_length=3)
    strengths: list[NarrativeClaim] = Field(max_length=3)
    watch_outs: list[NarrativeClaim] = Field(max_length=3)
    one_experiment: str = Field(max_length=260)
    narrative_version: int
    model: str = Field(max_length=80)
    generated_at: datetime
    dashes_rewritten: int
    invented_numbers_dropped: int
