# GENERATED by scripts/gen_report.py from spec/report.v1.json — DO NOT EDIT.
"""The builder report, server side.

`extra="forbid"` and the bounds below are the whole of the enforcement. Unlike the
narrative and the session analysis there is no schema on the other end that half-enforced
this already: the document is computed by `analysis/report.py`, so a field it grows
without the spec growing it is caught HERE, at the door, as a 422 rather than as a column
of nulls on somebody's phone.

The server does NOT compute this document and cannot. Three of its five blocks rest on
subagent sidecar transcripts, shell command text and prompt text, none of which leave the
machine (privacy/upload-contract.json). It validates and stores.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

REPORT_VERSION = 1

#: Character caps by size class; the spec's `max` on a string field names one of these.
REPORT_MAX_LENGTHS: dict[str, int] = {
    "label": 80,
    "reason": 200,
}

#: Legal values for every enum, in spec order. Named for the emitter in
#: scripts/gen_analysis.py, which writes validators that read these two tables by name;
#: renaming either here is a NameError at import, not a lint warning.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "trend_direction": ["up", "down", "steady"],
}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "ReportTrend": {"direction": "trend_direction"},
    "ReportAgentType": {},
    "ReportAgents": {},
    "ReportDay": {},
    "ReportContributions": {},
    "ReportGreen": {},
    "ReportQuality": {},
    "ReportPrompting": {},
    "BuilderReport": {},
}


class ReportTrend(BaseModel):
    model_config = ConfigDict(extra="forbid")

    metric: str = Field(max_length=80)
    label: str = Field(max_length=80)
    before: float
    now: float
    move: float
    direction: str
    good: bool | None = None
    sessions_before: int
    sessions_now: int

    @field_validator("direction")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportAgentType(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(max_length=80)
    agents: int


class ReportAgents(BaseModel):
    model_config = ConfigDict(extra="forbid")

    agents: int
    produced: int
    max_concurrent: int
    agent_seconds: float
    wall_seconds: float
    busy_seconds: float
    parallelism: float
    by_type: list[ReportAgentType] = Field(max_length=12)


class ReportDay(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day: str = Field(max_length=80)
    assisted: int
    alone: int


class ReportContributions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    assisted: int
    alone: int
    active_days: int
    longest_streak: int
    current_streak: int
    days: list[ReportDay] = Field(max_length=400)


class ReportGreen(BaseModel):
    model_config = ConfigDict(extra="forbid")

    n: int
    median_seconds: int
    worst_seconds: int
    median_attempts: int


class ReportQuality(BaseModel):
    model_config = ConfigDict(extra="forbid")

    runs: int
    passed: int | None = None
    failed: int | None = None
    first_try_rate: float | None = None
    time_to_green: ReportGreen | None = None
    reason: str | None = Field(default=None, max_length=200)


class ReportPrompting(BaseModel):
    model_config = ConfigDict(extra="forbid")

    attempts: int
    clean: int | None = None
    costly: int | None = None
    clean_share: float | None = None
    reason: str | None = Field(default=None, max_length=200)


class BuilderReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    report_version: int
    generated_at: datetime
    window_days: int
    trend_headline: str | None = Field(default=None, max_length=200)
    trends: list[ReportTrend] = Field(max_length=24)
    agents: ReportAgents | None = None
    contributions: ReportContributions | None = None
    quality: ReportQuality | None = None
    prompting: ReportPrompting | None = None
