# GENERATED by scripts/gen_shipped.py from spec/shipped.v1.json — DO NOT EDIT.
"""A build post, server side.

`extra="forbid"` and the bounds below are the enforcement half of
analysis/shipped_schema.json. The constrained decoder that produced the document
honours `required` and `additionalProperties`, but string lengths are checked HERE, on
the way into Postgres, or nowhere.

The server does NOT write this document and cannot: it rests on prompt text, which never
leaves the machine (privacy/upload-contract.json). It validates it and stores it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

SHIPPED_VERSION = 1

#: Character caps by size class; the spec's `max` on a string field names one of these.
SHIPPED_MAX_LENGTHS: dict[str, int] = {
    "line": 100,
    "sentence": 200,
    "para": 400,
    "short": 60,
}

#: Legal values for every enum, in spec order.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "stage": ["idea", "prototype", "working", "shipped", "maintaining"],
}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "ShippedChange": {},
    "ShippedPost": {"stage": "stage"},
}

#: Written by the runner after the model has spoken, never by the model itself.
STAMPED_FIELDS: list[str] = [
    "shipped_version",
    "model",
    "generated_at",
    "dashes_rewritten",
    "unsupported_claims_dropped",
]


class ShippedChange(BaseModel):
    model_config = ConfigDict(extra="forbid")

    text: str = Field(max_length=200)
    evidence: str | None = Field(default=None, max_length=200)


class ShippedPost(BaseModel):
    model_config = ConfigDict(extra="forbid")

    what: str = Field(max_length=100)
    why: str | None = Field(default=None, max_length=200)
    stage: str
    changes: list[ShippedChange] = Field(max_length=4)
    hard_part: str | None = Field(default=None, max_length=400)
    stack: list[Annotated[str, Field(max_length=60)]] = Field(max_length=6)
    demo: str | None = Field(default=None, max_length=200)
    next: str | None = Field(default=None, max_length=200)
    shipped_version: int
    model: str = Field(max_length=60)
    generated_at: datetime
    dashes_rewritten: int
    unsupported_claims_dropped: int

    @field_validator("stage")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v
