# GENERATED by scripts/gen_strip.py from spec/strip.v1.json — DO NOT EDIT.
"""Server-side strip decoding, used only by the sanity gates in routes/sync.py."""

from __future__ import annotations

import enum

SPEC_VERSION = 1
COLUMNS = 1024


class StripClass(enum.IntEnum):
    IDLE = 0
    PROMPTING = 1
    AGENT = 2
    HUMAN_EDIT = 3


class StripMarkKind(enum.IntEnum):
    PROMPT = 0
    COMMIT = 1
    COMPACT = 2


def unpack(byte: int) -> tuple[int, int]:
    """bits 0-1 class, bits 2-3 density."""
    return byte & 0b11, (byte >> 2) & 0b11


def non_idle_seconds(cols: bytes, span_seconds: float) -> float:
    """Seconds of non-idle columns. The server cross-checks this against the client's
    active_seconds and 422s on >5% disagreement — a strip that disagrees with its own
    session is a parser bug arriving as plausible data."""
    if not cols:
        return 0.0
    per_col = span_seconds / len(cols)
    return sum(per_col for b in cols if (b & 0b11) != StripClass.IDLE)
