/**
 * The animal pack — eight tiny two-colour creatures.
 *
 * Bit (`sprites.ts`) is the app's mascot and stays as it is: six palette roles, a face,
 * props. THIS pack is the opposite discipline, and the discipline is the point. Each
 * animal is a flat silhouette in exactly TWO colours — `b`, the body, and `d`, the
 * accent — with no outline, no shading and no third value. The reference is Anthropic's
 * Claude crab: it reads at 16 px because there is nothing in it to lose.
 *
 * Frames are the same 16×16 strings the mascot uses (`frames.ts`), so `validateFrame`,
 * `runsFor`, `mirror` and the whole renderer work here unchanged. `d` is the ACCENT
 * role, not necessarily the darker one — a grey cat has amber eyes (`palette.ts`).
 *
 * EVERY ANIMAL FACES FORWARD. The pack shipped with four head-on (crab, octopus, cat,
 * owl) and four in profile (dog, fox, whale, bee), and side by side the profiles read as a
 * different set of icons: no eye contact, no symmetry, and a silhouette that changes
 * meaning depending on which way it happens to point. The four were redrawn head-on. It
 * costs the obvious side-view gestures — a tail wagging across the frame, a brush
 * sweeping — and buys a pack that looks like one pack, which is the entire job of an icon
 * set. The gestures that replaced them are in the per-animal notes below.
 *
 * Three rules keep the pack subtle, and all three are tested:
 *
 *   1. A loop is 10 to 12 frames, and every frame moves exactly ONE part of the animal.
 *      That is the whole trick and it is worth stating plainly: the frames are generated
 *      from a base pose plus independent CHANNELS (claws, legs, eyelids, tail, wings),
 *      and a loop is a list of moves, one per beat, each changing one channel to an
 *      adjacent state. Ten beats of layered motion, none of them a redraw.
 *   2. Consecutive frames differ by at most 8 pixels — one claw, a pair of eyelids, a
 *      tail tip. Whole-body movement is NOT drawn into the frames; it is the renderer's
 *      1-pixel `drift` (`ANIMAL_MOTION` in `motion.ts`), so a crab sidesteps and a bee
 *      hovers without every frame change repainting the animal.
 *   3. Two animals must not share a silhouette. The dog's ears hang and the fox's stand
 *      up; that one difference is what tells them apart head-on at 16 px, so neither is
 *      free to borrow the other's.
 *
 * A transparent pixel inside a body reads as the background — that is how eyes and the
 * gaps between a bee's stripes are drawn, and it costs no third colour.
 */

import type { Frame } from './frames';

export type { Frame } from './frames';

/**
 * The pack, in presentation order: the picker in Settings and the contact sheet both
 * read this list, so the order here is the order a person sees.
 */
export const ANIMALS = [
  'crab',
  'octopus',
  'dog',
  'cat',
  'owl',
  'fox',
  'whale',
  'bee',
] as const;

export type Animal = (typeof ANIMALS)[number];

/** The only two glyphs an animal frame may draw. See the module note on `d`. */
export const ANIMAL_GLYPHS = ['b', 'd'] as const;
export type AnimalGlyph = (typeof ANIMAL_GLYPHS)[number];

/** Display names. Lower case, because every other caption in the app is. */
export const ANIMAL_LABELS: Record<Animal, string> = {
  crab: 'crab',
  octopus: 'octopus',
  dog: 'dog',
  cat: 'cat',
  owl: 'owl',
  fox: 'fox',
  whale: 'whale',
  bee: 'bee',
};

// ─── crab ────────────────────────────────────────────────────────────────────────────────
// Claws snip open and shut, the eight legs step through three positions, and the
// eyestalks blink once a loop. The sidestep itself stays the renderer's 1 px drift.

const CRAB: Frame[] = [
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'b.bb........bb.b',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d..d....d..d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bb.b........b.bb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d..d....d..d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bb.b........b.bb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '...d.d....d.d...',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bbbb........bbbb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '...d.d....d.d...',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bbbb........bbbb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d...d..d...d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bbbb........bbbb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbbbbbbbbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d...d..d...d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bbbb........bbbb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d...d..d...d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bb.b........b.bb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '..d...d..d...d..',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'bb.b........b.bb',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '...d.d....d.d...',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb..........bb.',
    'bbbb........bbbb',
    'b.bb........bb.b',
    '.bb...bbbb...bb.',
    '..bb.bbbbbb.bb..',
    '...bbdbbbbdbb...',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '...b.b.bb.b.b...',
    '...d.d....d.d...',
    '................',
    '................',
  ],
];

// ─── octopus ─────────────────────────────────────────────────────────────────────────────
// The mantle is still; the arms wave through four curls, out and back, and the eyes
// close once while they are mid-stroke.

const OCTOPUS: Frame[] = [
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '.bb..bb..bb..bb.',
    '.d....d..d....d.',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..d...d..d...d..',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '...bbbb..bbbb...',
    '...d..d..d..d...',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '...bbbb..bbbb...',
    '...bbbb..bbbb...',
    '...d..d..d..d...',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '...bbbb..bbbb...',
    '...bbbb..bbbb...',
    '...d..d..d..d...',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '...bbbb..bbbb...',
    '...bbbb..bbbb...',
    '...d..d..d..d...',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '...bbbb..bbbb...',
    '...d..d..d..d...',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..d...d..d...d..',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '.bb..bb..bb..bb.',
    '.d....d..d....d.',
    '................',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbddbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '...bbbbbbbbbb...',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..bb.bb..bb.bb..',
    '..d...d..d...d..',
    '................',
    '................',
    '................',
  ],
];

// ─── dog ─────────────────────────────────────────────────────────────────────────────────
// The tail tip swings out past one flank and then the other, two pixels at a time, the
// ears bounce on the far swing, and there is a blink at the top of the loop.

const DOG: Frame[] = [
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '.dbbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    'ddbbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '..dd.bbbbbb.dd..',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    'ddbbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '..dd.bbbbbb.dd..',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '.dbbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '..dd.bbbbbb.dd..',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbbd.',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbbdd',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbbdd',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbbdd',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
  [
    '................',
    '.....bbbbbb.....',
    '..ddbbbbbbbbdd..',
    '..ddb.bbbb.bdd..',
    '..ddb.bbbb.bdd..',
    '..ddbbbbbbbbdd..',
    '..ddbbddddbbdd..',
    '..dd.bbbbbb.dd..',
    '...d.bbbbbb.d...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbbd.',
    '..dd.bbbbbb.dd..',
    '................',
    '................',
  ],
];

// ─── cat ─────────────────────────────────────────────────────────────────────────────────
// The tail sweeps through four positions down the right side, one ear twitches, and the
// eyes shut once. Everything else holds: a sitting cat is mostly still.

const CAT: Frame[] = [
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb.bb....',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b....bb........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bbbbbbb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb...bb..',
    '..bbbbbbb..bb...',
    '..bbbbbbb..bb...',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb..bb...',
    '..bbbbbbb...bb..',
    '..bbbbbbb...bb..',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.bb....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb..bb...',
    '..bbbbbbb...bb..',
    '..bbbbbbb...bb..',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.b.....b........',
    '.bb...bb........',
    '.bbbbbbb........',
    '.bdbbbdb........',
    '.bbbbbbb........',
    '..bbbbb.........',
    '..bbbbbb........',
    '..bbbbbbb..bb...',
    '..bbbbbbb...bb..',
    '..bbbbbbb...bb..',
    '..bbbbbbbbbb....',
    '..dbbbbbbbd.....',
    '................',
    '................',
  ],
];

// ─── owl ─────────────────────────────────────────────────────────────────────────────────
// A real blink (half, shut, half), a head turn each way, the ear tufts flattening once,
// and a shuffle of the feet. The blink frames are held short by `holds`.

const OWL: Frame[] = [
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbddbb..',
    '..bddbbbbbddbb..',
    '..bbbbddbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..b..........b..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbddbbbbbddb..',
    '..bbddbbbbbddb..',
    '..bbbbbbddbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '....dd....dd....',
    '................',
  ],
  [
    '................',
    '................',
    '..bb........bb..',
    '..bbb......bbb..',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bddbbbbbbddb..',
    '..bddbbbbbbddb..',
    '..bbbbbddbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bdbbbbbbbbdb..',
    '..bdbbbbbbbbdb..',
    '...bbbbbbbbbb...',
    '....bbbbbbbb....',
    '...dd......dd...',
    '................',
  ],
];

// ─── fox ─────────────────────────────────────────────────────────────────────────────────
// One ear folds, then the other, the chest widens twice on the breath, and the eyes
// shut once between them.

const FOX: Frame[] = [
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '............b...',
    '.bbb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '...bbddddddbb...',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...bbbbbbbbbb...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b............',
    '..bb........bbb.',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....bbddddbb....',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
  [
    '...b........b...',
    '..bb........bb..',
    '..bdb......bdb..',
    '..bdbb....bbdb..',
    '...bbbbbbbbbb...',
    '...b..bbbb..b...',
    '...bbbbbbbbbb...',
    '...bbbbddbbbb...',
    '....bbddddbb....',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '...bbddddddbb...',
    '...bbbddddbbb...',
    '...bbbbbbbbbb...',
    '................',
    '................',
  ],
];

// ─── whale ───────────────────────────────────────────────────────────────────────────────
// The spout is the loop: a bud, a column, a plume, then it falls apart and clears. The
// flippers tuck once and there is a blink at the end.

const WHALE: Frame[] = [
  [
    '................',
    '................',
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.......dd.......',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '.......dd.......',
    '.......dd.......',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '......d..d......',
    '.......dd.......',
    '.......dd.......',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '.....d....d.....',
    '......d..d......',
    '.......dd.......',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '.....d....d.....',
    '......d..d......',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    '.bbbbbbbbbbbbbb.',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..b..bbbbbb..b..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbbbbbbbbb...',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    '..bbbbbbbbbbbb..',
    'bbbbbbbbbbbbbbbb',
    '.bbbbbbbbbbbbbb.',
    '..bbbbbbbbbbbb..',
    '...dddddddddd...',
    '....bbbbbbbb....',
    '................',
    '................',
  ],
];

// ─── bee ─────────────────────────────────────────────────────────────────────────────────
// The wings beat through five positions and back, twice a loop, the abdomen tapers on
// the breath, and the eyes close once between beats.

const BEE: Frame[] = [
  [
    '................',
    '................',
    '..dd........dd..',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '...d........d...',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '..dd........dd..',
    '.dddd..bb..dddd.',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '................',
    '.dddd..bb..dddd.',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '..dd........dd..',
    '.dddd..bb..dddd.',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '......bbbb......',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
  [
    '................',
    '................',
    '...d........d...',
    '.dddd......dddd.',
    '..dd...bb...dd..',
    '.....bbbbbb.....',
    '....b.bbbb.b....',
    '....b.bbbb.b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '....b......b....',
    '....bbbbbbbb....',
    '.....bbbbbb.....',
    '................',
    '................',
  ],
];

export const ANIMAL_FRAMES: Record<Animal, Frame[]> = {
  crab: CRAB,
  octopus: OCTOPUS,
  dog: DOG,
  cat: CAT,
  owl: OWL,
  fox: FOX,
  whale: WHALE,
  bee: BEE,
};

export function framesForAnimal(animal: Animal): Frame[] {
  return ANIMAL_FRAMES[animal];
}

export function isAnimal(value: unknown): value is Animal {
  return typeof value === 'string' && (ANIMALS as readonly string[]).includes(value);
}

// ─── archetype → animal ──────────────────────────────────────────────────────────────

/**
 * One animal per builder archetype, so the profile screen can show a creature rather than
 * a word. These six keys are the six archetypes in `generated/analysis.ts` — the ones a
 * MODEL assigns to a single session. That file is generated from the spec, so a seventh
 * archetype breaks this table's type rather than silently falling through to the default.
 *
 * The obvious pairs first: an architect gets the owl, a velocity machine the bee, a
 * quality guardian the crab (it walks sideways and checks everything twice).
 *
 * NIGHT OWL DOES NOT GET THE OWL. The architect has it, and two archetypes sharing a
 * creature would make the picture ambiguous exactly where it is supposed to be the
 * shorthand — so the night owl gets the CAT, which is the other thing that is awake at
 * 3 a.m. The remaining two follow the same logic: an explorer gets the octopus (eight
 * arms in eight places) and a firefighter the fox (fast, and never where it was).
 */
export const ARCHETYPE_ANIMALS = {
  architect: 'owl',
  velocity_machine: 'bee',
  quality_guardian: 'crab',
  night_owl: 'cat',
  explorer: 'octopus',
  firefighter: 'fox',
} as const satisfies Record<string, Animal>;

/**
 * The two archetypes the CORPUS profile can reach that a single session cannot.
 *
 * `analysis/profile.py:ARCHETYPE_RULES` scores a whole corpus deterministically, and its
 * six names are not the same six the model picks from per session: it can return
 * `director` (a high autonomy score: you brief and leave) and `skeptic` (test runs per
 * active hour), neither of which is in the spec's per-session enum. Without these two
 * entries a director's profile would show the fallback crab and read as a bug.
 *
 * They are written out here rather than generated because the corpus rules are not in
 * `spec/analysis.v1.json` — they are computation, not a wire enum. The union of the two
 * tables is eight archetypes over the pack's eight animals, and the test asserts that
 * mapping stays one-to-one, so a new archetype on either side cannot quietly share a
 * creature with an existing one.
 */
export const CORPUS_ARCHETYPE_ANIMALS = {
  director: 'dog',
  skeptic: 'whale',
} as const satisfies Record<string, Animal>;

export type ArchetypeKey = keyof typeof ARCHETYPE_ANIMALS;

/** The animal shown when nobody has chosen one and there is no archetype yet. */
export const DEFAULT_ANIMAL: Animal = 'crab';

/**
 * The animal for an archetype. Anything unknown — no analysis yet, a null modal, an
 * archetype from a newer server — falls back to `DEFAULT_ANIMAL` rather than throwing:
 * a profile screen is not the place to discover a spec change.
 */
export function animalForArchetype(archetype: string | null | undefined): Animal {
  if (typeof archetype !== 'string') return DEFAULT_ANIMAL;
  const hit =
    (ARCHETYPE_ANIMALS as Record<string, Animal>)[archetype] ??
    (CORPUS_ARCHETYPE_ANIMALS as Record<string, Animal>)[archetype];
  return hit ?? DEFAULT_ANIMAL;
}

// ─── the picker ──────────────────────────────────────────────────────────────────────

export interface AnimalChoice {
  id: Animal;
  label: string;
}

/** Every animal, in pack order, ready for a Settings list. */
export function animalChoices(): AnimalChoice[] {
  return ANIMALS.map((id) => ({ id, label: ANIMAL_LABELS[id] }));
}

/**
 * What a person's saved choice resolves to: their own pick if it is still a real animal,
 * otherwise their archetype's. A stored id that no longer exists reads as "unset" rather
 * than rendering nothing.
 */
export function resolveAnimal(chosen: string | null | undefined, archetype?: string | null): Animal {
  return isAnimal(chosen) ? chosen : animalForArchetype(archetype);
}
