#!/usr/bin/env python3
"""Generate the privacy contract into Swift, Python, TypeScript, JSON and prose.

privacy/upload-contract.json is the ONLY hand-edited definition of what may leave the
machine. Everything below is derived from it, committed, and checked by
`make gen && git diff --exit-code` in CI.

The structural guarantee is the SERIALIZER, not the test: BuilderSync's SessionUpload
encodes through the generated `UploadField` CodingKey enum with a hand-written
encode(to:), and there is no synthesized Codable anywhere in that target. A field that
is not in this file is unrepresentable on the wire.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "privacy" / "upload-contract.json"
# The one structured field whose shape lives in a second spec. Its leaf paths are walked
# from there so the published field list stays exact; see analysis_leaf_paths().
ANALYSIS_SPEC = ROOT / "spec" / "analysis.v1.json"

SWIFT_BANNER = "// GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."
PY_BANNER = "# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."

SWIFT_TYPES = {
    "sha256hex": "String",
    "string": "String",
    "int": "Int",
    "bool": "Bool",
    "datetime": "Date",
    "enum": "String",
    "base64": "String",
    "marks": "[StripMarkWire]",
    "toolmap": "[String: Int]",
    "tokens": "TokenBucketsWire",
    "models": "[ModelShareWire]",
    "url": "String",
    # Lives in BuilderModel/Generated/AnalysisSpec.swift (gen_analysis.py), hence the
    # `import BuilderModel` in the generated Swift below.
    "analysis": "SessionAnalysis",
}
PY_TYPES = {
    "sha256hex": "Sha256Hex",
    "string": "str",
    "int": "int",
    "bool": "bool",
    # `AwareDatetime`, not `datetime`: the plain type accepts "2026-08-15T09:00:00" with no
    # offset, and the first `now(UTC) - naive` downstream (notify.plan) is a TypeError that
    # escapes the upload transaction and turns one bad session into a 500 for the whole
    # batch. The Mac encodes every Date with `.iso8601`, which always carries `Z`.
    "datetime": "AwareDatetime",
    "enum": "str",
    "base64": "str",
    "marks": "list[StripMarkWire]",
    "toolmap": "dict[str, int]",
    "tokens": "TokenBucketsWire",
    "models": "list[ModelShareWire]",
    "url": "str",
    "analysis": "SessionAnalysis",
}
TS_TYPES = {
    "sha256hex": "string",
    "string": "string",
    "int": "number",
    "bool": "boolean",
    "datetime": "string",
    "enum": "string",
    "base64": "string",
    "marks": "StripMarkWire[]",
    "toolmap": "Record<string, number>",
    "tokens": "TokenBucketsWire",
    "models": "ModelShareWire[]",
    "url": "string",
    "analysis": "SessionAnalysis",
}


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def fields(c: dict) -> list[dict]:
    return c["fields"]


# --------------------------------------------------------------------------- swift
def gen_swift(c: dict) -> str:
    fs = fields(c)
    # Each case carries the Swift type the hand-written payload is expected to encode
    # through it, so a reader of this file can see the whole wire shape without opening
    # UploadPayload.swift. `?` marks a field that is omitted — never sent as null — when
    # absent.
    cases = "\n".join(
        f'    case {f["name"]}  // {SWIFT_TYPES[f["type"]]}{"?" if f.get("nullable") else ""}'
        for f in fs
    )

    def mode_set(mode: str) -> str:
        names = [f'.{f["name"]}' for f in fs if mode in f["modes"]]
        return "[\n        " + ",\n        ".join(names) + ",\n    ]"

    enums = "\n".join(
        f'        "{f["name"]}": {json.dumps(sorted(f["values"]))},'
        for f in fs
        if f["type"] == "enum"
    )

    return f"""{SWIFT_BANNER}

// BuilderModel supplies `SessionAnalysis` (Generated/AnalysisSpec.swift), the value type
// behind the `analysis` key. It is the only wire type not defined in this file.
import BuilderModel
import Foundation

/// Every key that may appear on the wire. `SessionUpload` encodes through this and only
/// this, with a hand-written `encode(to:)` and no synthesized `Codable`, so a field that
/// is not a case here is *unrepresentable* — adding a stored property to a model cannot
/// change the payload.
public enum UploadField: String, CodingKey, CaseIterable, Sendable {{
{cases}
}}

/// Per-repo visibility. `excluded` is deliberately not a mode: an excluded repo produces
/// zero uploads, and if ANY event in a session resolves to an excluded repo the entire
/// session is dropped rather than partially uploaded.
public enum PrivacyMode: String, Sendable, CaseIterable {{
    case publicRepo = "public"
    case anonymous

    public var allowedFields: Set<UploadField> {{
        switch self {{
        case .publicRepo: return UploadContract.publicFields
        case .anonymous:  return UploadContract.anonymousFields
        }}
    }}
}}

public enum UploadContract {{
    public static let version = {c["version"]}

    public static let publicFields: Set<UploadField> = {mode_set("public")}

    public static let anonymousFields: Set<UploadField> = {mode_set("anonymous")}

    /// Legal values for every enum-typed field, so a typo becomes a test failure here
    /// rather than a 422 from the server on the user's first sync.
    public static let enumValues: [String: [String]] = [
{enums}
    ]
}}

// MARK: - Wire value types

public struct StripMarkWire: Codable, Sendable, Equatable {{
    public let ms: Int
    public let k: Int
    public init(ms: Int, k: Int) {{ self.ms = ms; self.k = k }}
}}

/// Five separate buckets. There is no `total` — `cache_read` IS billed, at a reduced
/// rate, and on a cache-heavy agentic workload it dominates the input side, so a single
/// summed field would silently pick a definition.
public struct TokenBucketsWire: Codable, Sendable, Equatable {{
    public let input: Int
    public let output: Int
    public let cacheRead: Int
    public let cacheWrite5m: Int
    public let cacheWrite1h: Int

    enum CodingKeys: String, CodingKey {{
        case input, output
        case cacheRead = "cache_read"
        case cacheWrite5m = "cache_w5m"
        case cacheWrite1h = "cache_w1h"
    }}

    public init(input: Int, output: Int, cacheRead: Int, cacheWrite5m: Int, cacheWrite1h: Int) {{
        self.input = input; self.output = output; self.cacheRead = cacheRead
        self.cacheWrite5m = cacheWrite5m; self.cacheWrite1h = cacheWrite1h
    }}
}}

public struct ModelShareWire: Codable, Sendable, Equatable {{
    public let modelID: String
    public let outputTokenShare: Double

    enum CodingKeys: String, CodingKey {{
        case modelID = "model_id"
        case outputTokenShare = "output_token_share"
    }}

    public init(modelID: String, outputTokenShare: Double) {{
        self.modelID = modelID; self.outputTokenShare = outputTokenShare
    }}
}}
"""


# -------------------------------------------------------------------------- python
def gen_py(c: dict) -> str:
    fs = fields(c)
    lines = []
    for f in fs:
        t = PY_TYPES[f["type"]]
        if f.get("nullable"):
            lines.append(f'    {f["name"]}: {t} | None = None')
        else:
            lines.append(f'    {f["name"]}: {t}')
    body = "\n".join(lines)

    enum_fields = [f for f in fs if f["type"] == "enum"]
    enum_table = "\n".join(
        '    "%s": %s,' % (f["name"], json.dumps(sorted(f["values"]))) for f in enum_fields
    )
    enum_names = ", ".join('"%s"' % f["name"] for f in enum_fields)
    vtext = (
        f"    @field_validator({enum_names})\n"
        "    @classmethod\n"
        "    def _validate_enum(cls, v, info):\n"
        "        allowed = ENUM_VALUES.get(info.field_name)\n"
        "        if v is not None and allowed is not None and v not in allowed:\n"
        "            raise ValueError(\n"
        "                '%s=%r is not one of %r' % (info.field_name, v, allowed)\n"
        "            )\n"
        "        return v\n"
    )

    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]), indent=4)
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]), indent=4)

    return f'''{PY_BANNER}
"""The wire contract, server side. `extra="forbid"` is the belt-and-suspenders half of
the guarantee: even a hostile or stale client cannot push an undeclared field into
Postgres. The client-side half is that undeclared fields are unrepresentable at all."""

from __future__ import annotations

import re
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

# Generated by scripts/gen_analysis.py from spec/analysis.v1.json. `extra="forbid"` at
# every nesting level there, so an undeclared key inside `analysis` is as unstorable as
# an undeclared top-level field here.
from .analysis_spec import SessionAnalysis

CONTRACT_VERSION = {c["version"]}

_SHA256 = re.compile(r"^[0-9a-f]{{64}}$")
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{{64}}$")]

PUBLIC_FIELDS = {pub}

ANONYMOUS_FIELDS = {anon}

#: Legal values for every enum-typed field, so a client typo is a 422 with a useful
#: message rather than a constraint violation deep in a batch insert.
ENUM_VALUES: dict[str, list[str]] = {{
{enum_table}
}}


class StripMarkWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ms: int
    k: int


class TokenBucketsWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    input: int
    output: int
    cache_read: int
    cache_w5m: int
    cache_w1h: int


class ModelShareWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    model_id: str
    output_token_share: float


class SessionUpload(BaseModel):
    model_config = ConfigDict(extra="forbid")

{body}

{vtext}
'''


# ---------------------------------------------------------------------- typescript
def gen_ts(c: dict) -> str:
    fs = fields(c)
    lines = []
    for f in fs:
        t = TS_TYPES[f["type"]]
        # A nullable field is omitted by the Mac when absent, and a server that echoes a
        # stored row may hand it back as null. `?: T | null` is the only annotation under
        # which both are legal reads.
        nullable = bool(f.get("nullable"))
        opt = "?" if nullable else ""
        t = f"{t} | null" if nullable else t
        doc = f'  /** {f["doc"]} */\n' if f.get("doc") else ""
        lines.append(f'{doc}  {f["name"]}{opt}: {t};')
    body = "\n".join(lines)
    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]))
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]))
    return f"""{SWIFT_BANNER.replace('Swift', 'TypeScript')}

import type {{ SessionAnalysis }} from './analysis';

export const CONTRACT_VERSION = {c["version"]};

export interface StripMarkWire {{ ms: number; k: number; }}
export interface TokenBucketsWire {{
  input: number; output: number;
  cache_read: number; cache_w5m: number; cache_w1h: number;
}}
export interface ModelShareWire {{ model_id: string; output_token_share: number; }}

/** The complete set of fields the phone can ever receive for a session. */
export interface SessionWire {{
{body}
}}

export const PUBLIC_FIELDS = {pub} as const;
export const ANONYMOUS_FIELDS = {anon} as const;
"""


# ------------------------------------------------------------------------- prose
def gen_privacy_md(c: dict) -> str:
    fs = fields(c)
    rows = []
    for f in fs:
        modes = "public + anonymous" if len(f["modes"]) == 2 else f'**{f["modes"][0]} repos only**'
        doc = f.get("doc", "")
        rows.append(f'| `{f["name"]}` | {f["type"]} | {modes} | {doc} |')
    table = "\n".join(rows)

    return f"""<!-- GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT. -->

# What Builder sends, and what it does not

Builder reads the logs your AI coding tools already write to your own disk. Almost all of
that never moves. This page is generated directly from the file that defines the network
payload, so it cannot drift from the code: if a field is not in this table, the app has no
way to represent it on the wire.

## Never leaves your machine

Your prompts. The model's replies. Its thinking. Anything you or the model typed into a
file. Diffs and patches. File contents. **File paths, and file names.** Directory names.
Commit messages. Commit SHAs. Branch names. Your working directory. Your git remote URL.
The names of repositories you have not marked public. MCP server names. Terminal commands
and their output. Environment variables. URLs fetched. Your hostname. Your IP.

Not redacted versions of these. Not excerpts. There is no code path that sends them —
with one opt-in exception, **Session analysis**, described in its own section below. It is
the only field in the table that carries prose, and it is off unless you turn it on.

## What does leave, if you sign in

Every field, in full. `{c["version"]}` is the contract version.

| Field | Type | Sent for | What it is |
|---|---|---|---|
{table}

## Per-repository control

Every repository is **anonymous** by default: its sessions sync as a shape and a set of
counts, with no name attached. You can set a repository to **public** — which adds only
`repo_name`, `title` and `title_source` — or to **excluded**, which sends nothing at all.
If a single session touched an excluded repository, the whole session is dropped rather
than partially uploaded.

Titles come from the title your coding tool **already wrote to your disk**. Builder does
not send your prompts to a model to generate one. There is no such endpoint.

## Session analysis

The `analysis` field is the deliberate exception to the rule above, and it is opt-in for
exactly that reason.

When a session finishes, Builder can ask **your own Claude Code**, on your own machine, to
read a digest of the transcript and write a short account of it: what got built, how you
steered the agent, where the friction was. That is model-written prose. It may name files
and features, because that is what the session was about. It is produced locally — nothing
is sent to a third party to be summarised — and its shape is fixed by
`spec/analysis.v1.json`: every string has a length cap, and a document with an undeclared
key is rejected by the server rather than stored.

It **never includes your raw prompts**. The one place a prompt can appear is
`decision_patterns[].prompt_excerpt`: a short verbatim quote, at most 160 characters,
chosen to show a pattern in how you directed the agent. Nothing else in the document
quotes you.

Private by default. On the server it is readable only by your account, under the same row
level security as everything else, and it leaves your account only when you share that
session. Turn analysis upload off and the field is not sent at all — omitted, not sent as
empty.

## Check it yourself

Do not take the above on faith. The agent is open source and these commands run locally.

```bash
# 1. Print every byte the agent would send. Sends nothing.
builder sync --dry-run --print-payload | jq

# 2. Diff its actual keys against this page, in both directions.
#    `leaf_paths` expands the five structured fields (tokens, models, strip_marks,
#    tool_calls, analysis) so a scalar-path walk lines up exactly. tool_calls keys are
#    tool names, so they are normalised to the wildcard the contract publishes. List
#    indices are stripped both mid-path (features.0.name) and trailing (tags.0).
builder sync --dry-run --print-payload \\
  | jq -r '[paths(scalars)] | .[] | join(".")' \\
  | sed 's/^sessions\\.[0-9]*\\.//' \\
  | sed 's/\\.[0-9][0-9]*\\./\\./g' \\
  | sed 's/\\.[0-9][0-9]*$//' \\
  | sed 's/^tool_calls\\..*/tool_calls.<allowlisted tool name>/' \\
  | sort -u > /tmp/actual
curl -s "$BUILDER_BASE_URL/upload-fields.json" | jq -r '.leaf_paths[]' | sort -u > /tmp/declared

# Anything on the left that is not on the right is a field we send and did not declare.
comm -23 /tmp/actual /tmp/declared

# 3. Pick a phrase you typed to your agent today. Go looking for it.
builder sync --dry-run --print-payload | grep -i "that phrase"   # no output, exit 1

# 4. Trust none of the above. Builder does not certificate-pin, on purpose.
mitmproxy -p 8080 &
HTTPS_PROXY=http://127.0.0.1:8080 builder sync
```

## Repository hashing: the honest limit

Repositories are identified by an HMAC of the normalized git origin URL. The key is a
**global constant, identical for every user** — matching the same repository across two
machines requires both to derive the same hash. It ships inside an open-source binary and
is **not secret**.

The hash defeats casual exposure and makes a database dump unreadable. It does **not**
survive a dictionary attack against public repository names. If you need real secrecy, set
the repository to `excluded`: it is never hashed, never uploaded, and never parsed again.
Private set intersection is the correct fix and is not built.

## Permissions

Builder does not require Full Disk Access, Screen Recording, or Accessibility, and does not
ask for them. It reads `~/.claude`, `~/.codex`, `~/.cursor` and Cursor's application support
directory, none of which are protected by those permissions today. If a future macOS release
restricts one of them, Builder will tell you which one and why, and will keep working on the
others.
"""


def analysis_leaf_paths(prefix: str) -> list[str]:
    """Every scalar path a SessionAnalysis document can produce, under `prefix`.

    Walked from spec/analysis.v1.json rather than typed out, so a field added to the
    analysis spec is published here on the next `make gen` without anyone remembering to.
    The path shapes mirror what the verification command's jq/sed pipeline produces:

      object   -> prefix.field.child           (build_style.planning)
      list of objects -> prefix.field.child    (features.0.name, index stripped mid-path)
      list of scalars -> prefix.field          (tags.0, trailing index stripped)
      map keyed by enum -> one path per key    (work_mix.feature ... work_mix.ops)
      scalar   -> prefix.field                 (nullable ones included: null is a scalar)
    """
    s = json.loads(ANALYSIS_SPEC.read_text())

    def walk(owner_fields: list[dict], at: str) -> list[str]:
        out: list[str] = []
        for f in owner_fields:
            path = f"{at}.{f['name']}"
            t = f["type"]
            if t == "object":
                out += walk(s["objects"][f["item"]], path)
            elif t == "list" and f["item"] in s["objects"]:
                out += walk(s["objects"][f["item"]], path)
            elif t == "map":
                out += [f"{path}.{k}" for k in s["enums"][f["key"]]]
            else:
                out.append(path)
        return out

    return walk(s["fields"], prefix)


def main() -> None:
    c = json.loads(SPEC.read_text())
    print("gen_contract.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderSync/Generated/UploadContract.swift", gen_swift(c))
    write(ROOT / "server/builder/contract.py", gen_py(c))
    write(ROOT / "mobile/src/generated/contract.ts", gen_ts(c))
    # Published as BOTH the top-level names and the expanded leaf paths.
    #
    # The first version published only top-level names, and the verification command on
    # the privacy page — which walks every scalar path with jq — then reported
    # `tokens.input` and `strip_marks[].ms` as "sent but not declared". They are not: they
    # are the insides of declared structured fields. But a verification command that cries
    # leak on correct output is worse than none, because the first person to run it
    # publicly concludes the claim is false.
    #
    # `tool_calls` expands to whatever tool names a session used, so it is published as a
    # wildcard with its allowlist stated separately.
    #
    # `analysis` is the same trap one level deeper — 60-odd nested scalar paths — and it
    # is walked from its own spec rather than listed here, because a hand-kept list would
    # be exactly the kind that goes stale the first time the analysis spec grows.
    nested = {
        "tokens": ["input", "output", "cache_read", "cache_w5m", "cache_w1h"],
        "strip_marks": ["ms", "k"],
        "models": ["model_id", "output_token_share"],
        "tool_calls": ["<allowlisted tool name>"],
    }
    leaves: list[str] = []
    for f in fields(c):
        if f["name"] in nested:
            leaves += [f"{f['name']}.{child}" for child in nested[f["name"]]]
        elif f["type"] == "analysis":
            leaves += analysis_leaf_paths(f["name"])
        else:
            leaves.append(f["name"])

    write(
        ROOT / "server/builder/static/upload-fields.json",
        json.dumps(
            {
                "version": c["version"],
                "fields": sorted(f["name"] for f in fields(c)),
                "leaf_paths": sorted(leaves),
                "note": (
                    "`fields` are the top-level keys. `leaf_paths` expands the five "
                    "structured ones (tokens, models, strip_marks, tool_calls, analysis) "
                    "so a scalar-path walk of a real payload matches exactly, with list "
                    "indices stripped. tool_calls keys are tool names from a fixed "
                    "allowlist; unknown and MCP tools bucket to mcp_other / other. "
                    "analysis is opt-in and its shape is spec/analysis.v1.json."
                ),
            },
            indent=2,
        )
        + "\n",
    )
    write(ROOT / "PRIVACY.md", gen_privacy_md(c))


if __name__ == "__main__":
    main()
