#!/usr/bin/env python3
"""Generate the builder report into Pydantic and TypeScript.

spec/report.v1.json is the ONLY definition of what the profile's second document looks
like, and every emitter below is borrowed from scripts/gen_analysis.py so no two specs in
this repository can describe a `string, max 80` two different ways.

TWO OUTPUTS, NOT FOUR, and the missing ones are missing for a reason. There is no JSON
Schema because no model writes this document — every field is a number `analysis/report.py`
measured — so there is no constrained decoder to constrain. There is no Swift because the
report is computed by `python -m analysis report` on the machine that has the transcripts
and uploaded from there; the Mac renders the same JSON the phone does, through the server.

For the same reason there is no `stamped` rule here. `report_version` is written by the
runner like everywhere else, but there is no model that could have chosen it instead, so
splitting the fields into two lists would only add a distinction nothing acts on.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "report.v1.json"
TOP = "BuilderReport"

BANNER_TS = "// GENERATED by scripts/gen_report.py from spec/report.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_report.py from spec/report.v1.json — DO NOT EDIT."


def load() -> dict:
    s = json.loads(SPEC.read_text())
    names = [f["name"] for f in s["fields"]]
    assert "report_version" in names, (
        "report_version must be present: a stored document that cannot say which rules "
        "produced it is a document nobody can recompute or compare."
    )
    return s


def gen_py(s: dict) -> str:
    models = "\n\n".join(
        [ga.py_model(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.py_model(s, TOP, s["fields"])]
    ).rstrip("\n")
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in list(s["objects"].items()) + [(TOP, s["fields"])]
    )
    return f'''{BANNER_PY}
"""The builder report, server side.

`extra="forbid"` and the bounds below are the whole of the enforcement. Unlike the
narrative and the session analysis there is no schema on the other end that half-enforced
this already: the document is computed by `analysis/report.py`, so a field it grows
without the spec growing it is caught HERE, at the door, as a 422 rather than as a column
of nulls on somebody's phone.

The server does NOT compute this document and cannot. Three of its five blocks rest on
subagent sidecar transcripts, shell command text and prompt text, none of which leave the
machine (privacy/upload-contract.json). It validates and stores.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

REPORT_VERSION = {s["version"]}

#: Character caps by size class; the spec's `max` on a string field names one of these.
REPORT_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in spec order. Named for the emitter in
#: scripts/gen_analysis.py, which writes validators that read these two tables by name;
#: renaming either here is a NameError at import, not a lint warning.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}


{models}
'''


def gen_ts(s: dict) -> str:
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in s["enums"].items()
    )
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, TOP, s["fields"])]
    )
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    return f"""{BANNER_TS}

export const REPORT_VERSION = {s["version"]};

/** Character caps by size class; string fields below name one of these in their doc. */
export const REPORT_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{unions}

{interfaces}
"""


def main() -> None:
    s = load()
    print("gen_report.py")
    ga.write(ROOT / "server/builder/report_spec.py", gen_py(s))
    ga.write(ROOT / "mobile/src/generated/report.ts", gen_ts(s))


if __name__ == "__main__":
    main()
