#!/usr/bin/env python3
"""Generate the build-post schema into JSON Schema, Pydantic and TypeScript.

spec/shipped.v1.json is the ONLY definition of what a build post looks like, and every
emitter below is borrowed from scripts/gen_analysis.py so the two specs cannot describe a
`string, max 200` two different ways.

Same `stamped` rule as gen_narrative.py: a field the runner writes after the model has
spoken is not in the schema the model sees. A model that can write its own
`unsupported_claims_dropped` can write a zero.

There is no Swift output. A build post is drafted by `python -m analysis shipped` on the
machine with the transcripts and published from there; the Mac renders the same JSON the
phone does, through the server.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "shipped.v1.json"
TOP = "ShippedPost"

BANNER_TS = "// GENERATED by scripts/gen_shipped.py from spec/shipped.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_shipped.py from spec/shipped.v1.json — DO NOT EDIT."


def load() -> dict:
    s = json.loads(SPEC.read_text())
    stamped = [f["name"] for f in s["fields"] if f.get("stamped")]
    assert "shipped_version" in stamped, (
        "shipped_version must be stamped: it says which rules produced the document, "
        "so a model that chose it could claim rules it never followed."
    )
    return s


def model_fields(s: dict) -> list[dict]:
    """What the model is asked for: everything the runner does not stamp itself."""
    return [f for f in s["fields"] if not f.get("stamped")]


def gen_schema(s: dict) -> str:
    fs = model_fields(s)
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "GENERATED by scripts/gen_shipped.py from spec/shipped.v1.json — DO NOT "
            "EDIT. Handed to `claude -p --json-schema`."
        ),
        "title": TOP,
        # The version the stamped `shipped_version` gets. It is not a property of the
        # schema the model sees, because the model does not choose it, and it is not a
        # second constant in analysis/narrative.py, because that would be two
        # definitions of one number. `load_schema` strips it before the CLI sees it.
        "x-version": s["version"],
        "description": (
            "What somebody built, written so another builder would want to look. Every "
            "sentence describes work that is actually in the input: a technology the work "
            "never used, or a feature nothing shows, is the worst thing this document can "
            "contain, because it is a public claim the reader has no way to check."
        ),
        **ga.json_object(s, fs),
        "$defs": {name: ga.json_object(s, o) for name, o in s["objects"].items()},
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def gen_py(s: dict) -> str:
    # rstrip: `py_model` ends each class with a newline and the template adds its own, so
    # without this the file ends with a blank line and `ruff format --check` fails on a
    # file the header forbids anyone from fixing by hand.
    models = "\n\n".join(
        [ga.py_model(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.py_model(s, TOP, s["fields"])]
    ).rstrip("\n")
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    # `ga.py_model` emits a validator that reads these two tables by name whenever a model
    # has an enum field. gen_narrative.py never hit it because that spec has no enums;
    # this one does, and a generated module referencing tables it does not define is a
    # NameError at import, caught by the lint gate rather than by a user.
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in list(s["objects"].items()) + [(TOP, s["fields"])]
    )
    # One per line: the list is long enough that a single line trips the 100-column lint
    # CI runs, and a generated file that fails the lint gate is a red build nobody can fix
    # by hand (the header says DO NOT EDIT, and it means it).
    stamped = "\n".join(
        f"    {json.dumps(f['name'])}," for f in s["fields"] if f.get("stamped")
    )
    return f'''{BANNER_PY}
"""A build post, server side.

`extra="forbid"` and the bounds below are the enforcement half of
analysis/shipped_schema.json. The constrained decoder that produced the document
honours `required` and `additionalProperties`, but string lengths are checked HERE, on
the way into Postgres, or nowhere.

The server does NOT write this document and cannot: it rests on prompt text, which never
leaves the machine (privacy/upload-contract.json). It validates it and stores it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

SHIPPED_VERSION = {s["version"]}

#: Character caps by size class; the spec's `max` on a string field names one of these.
SHIPPED_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in spec order.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}

#: Written by the runner after the model has spoken, never by the model itself.
STAMPED_FIELDS: list[str] = [
{stamped}
]


{models}
'''


def gen_ts(s: dict) -> str:
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, TOP, s["fields"])]
    )
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    return f"""{BANNER_TS}

export const SHIPPED_VERSION = {s["version"]};

/** Character caps by size class; string fields below name one of these in their doc. */
export const SHIPPED_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{interfaces}
"""


def main() -> None:
    s = load()
    print("gen_shipped.py")
    ga.write(ROOT / "analysis/shipped_schema.json", gen_schema(s))
    ga.write(ROOT / "server/builder/shipped_spec.py", gen_py(s))
    ga.write(ROOT / "mobile/src/generated/shipped.ts", gen_ts(s))


if __name__ == "__main__":
    main()
