#!/usr/bin/env python3
"""Generate the strip-spec constants into Swift, TypeScript and Python.

spec/strip.v1.json is the ONLY place the class and mark ordinals live. Nobody hand-types
the integers, because a renderer fed the wrong ordinals paints every agent run in the
prompt colour and produces a plausible-looking strip that survives code review.

Run via `make gen`. CI runs `make gen && git diff --exit-code`.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "strip.v1.json"

BANNER = "// GENERATED by scripts/gen_strip.py from spec/strip.v1.json — DO NOT EDIT."
PY_BANNER = "# GENERATED by scripts/gen_strip.py from spec/strip.v1.json — DO NOT EDIT."


def load() -> dict:
    return json.loads(SPEC.read_text())


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


# --------------------------------------------------------------------------- swift
def gen_swift(s: dict) -> str:
    classes = s["classes"]
    marks = s["marks"]
    weights = s["classWeights"]

    cases = "\n".join(
        f"    case {name} = {ordinal}" for name, ordinal in sorted(classes.items(), key=lambda kv: kv[1])
    )
    mark_cases = "\n".join(
        f"    case {name} = {ordinal}" for name, ordinal in sorted(marks.items(), key=lambda kv: kv[1])
    )
    weight_rows = "\n".join(
        f"        case .{name}: return {float(weights[name])}" for name in sorted(classes, key=lambda k: classes[k])
    )
    thresholds = ", ".join(str(float(t)) for t in s["densityThresholdsEventsPerSec"])
    alphas = ", ".join(str(float(a)) for a in s["densityAlphas"])

    return f"""{BANNER}

import Foundation

/// Segment class for one strip column. Ordinals are wire format — see spec/strip.v1.json.
public enum StripClass: UInt8, Sendable, CaseIterable, Codable {{
{cases}
}}

/// Point-in-time marks, stored separately from columns so a 5-second prompt
/// cannot be resampled away.
public enum StripMarkKind: UInt8, Sendable, CaseIterable, Codable {{
{mark_cases}
}}

public enum StripSpec {{
    public static let version = {s["spec_version"]}
    public static let columns = {s["columns"]}

    /// Column fill is priority-weighted argmax over milliseconds, not raw argmax.
    /// MEASURED: a 71-minute session over 1024 columns is 4.2 s/column, so nearly every
    /// column holds several event types and raw argmax erases prompting entirely.
    public static func weight(_ c: StripClass) -> Double {{
        switch c {{
{weight_rows}
        }}
    }}

    public static let densityThresholdsEventsPerSec: [Double] = [{thresholds}]
    public static let densityAlphas: [Double] = [{alphas}]
    public static let markDedupeMinPx = {s["markDedupeMinPx"]}

    /// bits 0-1 class, bits 2-3 density, bits 4-7 reserved and MUST be 0.
    @inlinable
    public static func pack(_ c: StripClass, density: UInt8) -> UInt8 {{
        precondition(density < 4, "density is a 2-bit field")
        return (c.rawValue & 0b11) | ((density & 0b11) << 2)
    }}

    @inlinable
    public static func unpack(_ byte: UInt8) -> (klass: StripClass, density: UInt8) {{
        (StripClass(rawValue: byte & 0b11)!, (byte >> 2) & 0b11)
    }}

    /// Resampling is ALWAYS nearest-neighbour on column centres. Never a box filter —
    /// averaging categorical ordinals is meaningless.
    public static func resample(_ cols: [UInt8], to width: Int) -> [UInt8] {{
        guard width > 0, !cols.isEmpty else {{ return [] }}
        return (0..<width).map {{ i in
            let centre = (Double(i) + 0.5) / Double(width)
            let src = min(cols.count - 1, max(0, Int(centre * Double(cols.count))))
            return cols[src]
        }}
    }}
}}
"""


# ---------------------------------------------------------------------- typescript
def gen_ts(s: dict) -> str:
    classes = s["classes"]
    marks = s["marks"]
    weights = s["classWeights"]

    cls = "\n".join(f"  {name}: {ordinal}," for name, ordinal in sorted(classes.items(), key=lambda kv: kv[1]))
    mk = "\n".join(f"  {name}: {ordinal}," for name, ordinal in sorted(marks.items(), key=lambda kv: kv[1]))
    wt = "\n".join(f"  {classes[name]}: {float(weights[name])}," for name in sorted(weights, key=lambda k: classes[k]))

    return f"""{BANNER}

export const SPEC_VERSION = {s["spec_version"]};
export const COLUMNS = {s["columns"]};

/** Segment class for one strip column. Ordinals are wire format — see spec/strip.v1.json. */
export const StripClass = {{
{cls}
}} as const;
export type StripClass = (typeof StripClass)[keyof typeof StripClass];

export const StripMarkKind = {{
{mk}
}} as const;
export type StripMarkKind = (typeof StripMarkKind)[keyof typeof StripMarkKind];

/** Priority-weighted argmax over milliseconds, keyed by class ordinal. */
export const CLASS_WEIGHT: Record<number, number> = {{
{wt}
}};

export const DENSITY_THRESHOLDS_EVENTS_PER_SEC = {json.dumps(s["densityThresholdsEventsPerSec"])};
export const DENSITY_ALPHAS = {json.dumps(s["densityAlphas"])};
export const MARK_DEDUPE_MIN_PX = {s["markDedupeMinPx"]};

/** bits 0-1 class, bits 2-3 density, bits 4-7 reserved and MUST be 0. */
export function pack(klass: StripClass, density: number): number {{
  if (density < 0 || density > 3) throw new Error('density is a 2-bit field');
  return (klass & 0b11) | ((density & 0b11) << 2);
}}

export function unpack(byte: number): {{ klass: StripClass; density: number }} {{
  return {{ klass: (byte & 0b11) as StripClass, density: (byte >> 2) & 0b11 }};
}}

/**
 * Nearest-neighbour on column centres. NEVER a box filter — averaging categorical
 * ordinals is meaningless, and this must agree byte-for-byte with StripSpec.resample
 * in Swift. spec/fixtures/*.json assert exactly that.
 */
export function resample(cols: Uint8Array | number[], width: number): number[] {{
  const n = cols.length;
  if (width <= 0 || n === 0) return [];
  const out: number[] = new Array(width);
  for (let i = 0; i < width; i++) {{
    const centre = (i + 0.5) / width;
    const src = Math.min(n - 1, Math.max(0, Math.floor(centre * n)));
    out[i] = cols[src];
  }}
  return out;
}}

export const PRESETS = {json.dumps(s["presets"], indent=2)} as const;
"""


# -------------------------------------------------------------------------- python
def gen_py(s: dict) -> str:
    classes = s["classes"]
    marks = s["marks"]
    cls = "\n".join(f"    {n.upper()} = {o}" for n, o in sorted(classes.items(), key=lambda kv: kv[1]))
    mk = "\n".join(f"    {n.upper()} = {o}" for n, o in sorted(marks.items(), key=lambda kv: kv[1]))
    return f'''{PY_BANNER}
"""Server-side strip decoding, used only by the sanity gates in routes/sync.py."""

from __future__ import annotations

import enum

SPEC_VERSION = {s["spec_version"]}
COLUMNS = {s["columns"]}


class StripClass(enum.IntEnum):
{cls}


class StripMarkKind(enum.IntEnum):
{mk}


def unpack(byte: int) -> tuple[int, int]:
    """bits 0-1 class, bits 2-3 density."""
    return byte & 0b11, (byte >> 2) & 0b11


def non_idle_seconds(cols: bytes, span_seconds: float) -> float:
    """Seconds of non-idle columns. The server cross-checks this against the client's
    active_seconds and 422s on >5% disagreement — a strip that disagrees with its own
    session is a parser bug arriving as plausible data."""
    if not cols:
        return 0.0
    per_col = span_seconds / len(cols)
    return sum(per_col for b in cols if (b & 0b11) != StripClass.IDLE)
'''


def main() -> None:
    s = load()
    print("gen_strip.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderModel/Generated/StripSpec.swift", gen_swift(s))
    write(ROOT / "mobile/src/generated/strip.ts", gen_ts(s))
    write(ROOT / "server/builder/strip.py", gen_py(s))


if __name__ == "__main__":
    main()
