#!/usr/bin/env python3
"""Generate design tokens into Swift and TypeScript.

COLOUR SPACE IS LOAD-BEARING. SwiftUI's bare Color(red:green:blue:) is Display P3 while
react-native-svg takes sRGB hex, so the Mac card would come out visibly more saturated
than the byte-identical phone card. The Swift emitted here is plain sRGB components;
BuilderUI/StripPalette.swift is the only place that turns them into Color, and it always
uses Color(.sRGB, ...).
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "design" / "tokens.json"
BANNER = "// GENERATED by scripts/gen_tokens.py from design/tokens.json — DO NOT EDIT."


def hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(round(int(h[i : i + 2], 16) / 255.0, 6) for i in (0, 2, 4))  # type: ignore[return-value]


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def swift_rgb(name: str, pair: dict) -> str:
    lr, lg, lb = hex_to_rgb(pair["light"])
    dr, dg, db = hex_to_rgb(pair["dark"])
    return (
        f'    public static let {name} = SRGBPair(\n'
        f'        light: SRGB(r: {lr}, g: {lg}, b: {lb}),  // {pair["light"]}\n'
        f'        dark:  SRGB(r: {dr}, g: {dg}, b: {db})   // {pair["dark"]}\n'
        f'    )'
    )


def gen_swift(t: dict) -> str:
    def group(key: str) -> str:
        entries = {k: v for k, v in t[key].items() if not k.startswith("_")}
        body = "\n".join(swift_rgb(name, pair) for name, pair in entries.items())
        return f"    // MARK: {key}\n{body}"

    graph_light = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["light"]
    )
    graph_dark = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["dark"]
    )

    card = t["card"]
    space = "\n".join(
        f"    public static let {k} = {float(v)}" for k, v in t["space"].items() if not k.startswith("_")
    )
    radius = "\n".join(
        f"    public static let {k} = {float(v)}" for k, v in t["radius"].items() if not k.startswith("_")
    )

    return f"""{BANNER}

import Foundation

/// An sRGB colour. NOT Display P3 — see the note in design/tokens.json. The only place
/// these become SwiftUI Colors is BuilderUI/StripPalette.swift, via Color(.sRGB, ...).
public struct SRGB: Sendable, Equatable {{
    public let r: Double, g: Double, b: Double
    public init(r: Double, g: Double, b: Double) {{ self.r = r; self.g = g; self.b = b }}
}}

public struct SRGBPair: Sendable, Equatable {{
    public let light: SRGB, dark: SRGB
    public init(light: SRGB, dark: SRGB) {{ self.light = light; self.dark = dark }}
    public func resolve(dark isDark: Bool) -> SRGB {{ isDark ? dark : light }}
}}

public enum DesignTokens {{

{group("strip")}

{group("mark")}

{group("surface")}

    // MARK: graph — coloured by ACTIVE HOURS, absolute buckets (see Tuning.graphHourBuckets)
    public static let graphLight: [SRGB] = [{graph_light}]
    public static let graphDark:  [SRGB] = [{graph_dark}]

    // MARK: layout
    public enum Space {{
{space}
    }}
    public enum Radius {{
{radius}
    }}
    public enum Card {{
        public static let landscape = (w: {card["landscape"]["w"]}.0, h: {card["landscape"]["h"]}.0)
        public static let portrait  = (w: {card["portrait"]["w"]}.0,  h: {card["portrait"]["h"]}.0)
        public static let scale     = {float(card["scale"])}
    }}
}}
"""


def gen_ts(t: dict) -> str:
    clean = {k: v for k, v in t.items() if not k.startswith("_")}
    for group in ("strip", "mark", "surface"):
        clean[group] = {k: v for k, v in clean[group].items() if not k.startswith("_")}
    clean["graph"] = {"levels": t["graph"]["levels"]}
    clean["type"] = {k: v for k, v in t["type"].items() if not k.startswith("_")}
    clean["card"] = {k: v for k, v in t["card"].items() if not k.startswith("_")}
    return f"""{BANNER}

export const tokens = {json.dumps(clean, indent=2)} as const;

export type Scheme = 'light' | 'dark';

/** All values are sRGB hex, which is what react-native-svg expects. */
export function pick(pair: {{ light: string; dark: string }}, scheme: Scheme): string {{
  return pair[scheme];
}}
"""


def main() -> None:
    t = json.loads(SPEC.read_text())
    print("gen_tokens.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderModel/Generated/DesignTokens.swift", gen_swift(t))
    write(ROOT / "mobile/src/generated/tokens.ts", gen_ts(t))


if __name__ == "__main__":
    main()
