#!/usr/bin/env python3
"""Generate the session-analysis schema into Swift, TypeScript, Python and JSON Schema.

spec/analysis.v1.json is the ONLY definition of what a model-written session analysis
looks like. Everything below is derived from it, committed, and checked by
`make gen && git diff --exit-code` in CI. The four outputs are one schema in four
notations; if any of them could drift, the phone would render a field the server had
rejected, or the server would store a value the prompt never allowed.

Two rules the outputs share:

  * Enum values keep SPEC ORDER everywhere — Swift `CaseIterable`, the TypeScript
    unions, the Python table and the JSON Schema. `planning` reads none < light <
    explicit_plan < plan_mode; sorting would erase that and no test would notice.

  * Bounds are stated twice, on purpose. Every `double` in this spec is a unit-interval
    fraction (coverage, shares, confidence) and every `int` whose doc opens with `a-b`
    is a bounded score. Those bounds go into the JSON Schema as `minimum`/`maximum`/
    `maxLength`, AND into each property's `description`. The constrained decoder behind
    `claude -p --json-schema` honours `enum`, `const`, `required` and
    `additionalProperties: false`, but numeric and string-length keywords are not part of
    what it can enforce — the model reads the description, and Pydantic enforces the
    keyword on the way into Postgres. A schema that only said `maxLength: 90` would look
    enforced and be advisory.
"""

from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "analysis.v1.json"

SWIFT_BANNER = "// GENERATED by scripts/gen_analysis.py from spec/analysis.v1.json — DO NOT EDIT."
TS_BANNER = SWIFT_BANNER
PY_BANNER = "# GENERATED by scripts/gen_analysis.py from spec/analysis.v1.json — DO NOT EDIT."

TOP = "SessionAnalysis"

SHA256_PATTERN = r"^[0-9a-f]{64}$"

SWIFT_SCALARS = {
    "sha256hex": "String",
    "string": "String",
    "int": "Int",
    "double": "Double",
    "bool": "Bool",
    "datetime": "Date",
}
TS_SCALARS = {
    "sha256hex": "string",
    "string": "string",
    "int": "number",
    "double": "number",
    "bool": "boolean",
    "datetime": "string",
}
PY_SCALARS = {
    "sha256hex": "Sha256Hex",
    "string": "str",
    "int": "int",
    "double": "float",
    "bool": "bool",
    "datetime": "datetime",
}
JSON_SCALARS = {
    "sha256hex": {"type": "string", "pattern": SHA256_PATTERN},
    "string": {"type": "string"},
    "int": {"type": "integer"},
    "double": {"type": "number"},
    "bool": {"type": "boolean"},
    "datetime": {"type": "string", "format": "date-time"},
}

# Reserved words that would need backticks if a spec value ever collided with one.
# None do today; the escape exists so a future value like `default` fails to be a
# silent Swift syntax error rather than a silent behaviour change.
SWIFT_KEYWORDS = {
    "as", "associatedtype", "break", "case", "catch", "class", "continue", "default",
    "defer", "deinit", "do", "else", "enum", "extension", "fallthrough", "false",
    "fileprivate", "for", "func", "guard", "if", "import", "in", "init", "inout",
    "internal", "is", "let", "nil", "open", "operator", "private", "protocol", "public",
    "repeat", "rethrows", "return", "self", "static", "struct", "subscript", "super",
    "switch", "throw", "throws", "true", "try", "typealias", "var", "where", "while",
}

# An int is a bounded score when its doc opens with `a-b` ("0-100: how precisely ...").
RANGE_DOC = re.compile(r"^(\d+)-(\d+)\b")
# Every double in this spec is a fraction; this is what the assertion in load() checks.
FRACTION_DOC = re.compile(r"fraction|share|0-1")


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def load() -> dict:
    s = json.loads(SPEC.read_text())
    for owner, fs in all_fields(s):
        for f in fs:
            if f["type"] == "double" or (f["type"] == "map" and f["value"] == "double"):
                doc = f.get("doc", "")
                assert FRACTION_DOC.search(doc), (
                    f"{owner}.{f['name']} is a double whose doc ({doc!r}) does not say it is a "
                    "fraction. Every double here is emitted with bounds 0-1; either document "
                    "it as a fraction/share or teach gen_analysis.py a second double kind."
                )
    return s


def all_fields(s: dict) -> list[tuple[str, list[dict]]]:
    return [(name, fs) for name, fs in s["objects"].items()] + [(TOP, s["fields"])]


# ------------------------------------------------------------------------ naming
def camel(snake: str) -> str:
    head, *rest = snake.split("_")
    return head + "".join(w[:1].upper() + w[1:] for w in rest)


def pascal(snake: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in snake.split("_"))


def swift_ident(name: str) -> str:
    return f"`{name}`" if name in SWIFT_KEYWORDS else name


# ------------------------------------------------------------------------ bounds
def numeric_bounds(f: dict) -> tuple[int, int] | tuple[float, float] | None:
    if f["type"] == "double":
        return (0.0, 1.0)
    if f["type"] == "int":
        m = RANGE_DOC.match(f.get("doc", ""))
        if m:
            return (int(m.group(1)), int(m.group(2)))
    return None


def max_len(s: dict, f: dict) -> int | None:
    return s["max_lengths"][f["max"]] if "max" in f else None


def description(s: dict, f: dict) -> str:
    """The spec's doc plus every bound the schema keywords alone cannot enforce."""
    doc = f.get("doc", "")
    hints: list[str] = []
    t = f["type"]
    ml = max_len(s, f)
    if t == "string" and ml is not None:
        hints.append(f"max {ml} chars")
    if t == "list":
        if f["item"] == "string" and ml is not None:
            hints.append(f"each max {ml} chars")
        hints.append(
            f"{f['min_items']} to {f['max_items']} items"
            if f.get("min_items")
            else f"max {f['max_items']} items"
        )
    b = numeric_bounds(f)
    if b is not None and not RANGE_DOC.match(doc):
        lo, hi = b
        hints.append(f"{lo:g}-{hi:g}")
    if t == "map":
        hints.append(f"keys are {f['key']} values, each value 0-1")
    if t == "datetime":
        hints.append("ISO 8601")
    if t == "sha256hex":
        hints.append("64 lowercase hex chars")
    if not hints:
        return doc
    tail = "(" + ", ".join(hints) + ")"
    return f"{doc} {tail}" if doc else tail


# ------------------------------------------------------------------------- swift
def swift_type(s: dict, f: dict) -> str:
    t = f["type"]
    if t == "enum":
        base = pascal(f["values"])
    elif t == "object":
        base = f["item"]
    elif t == "list":
        item = f["item"]
        base = f"[{item if item in s['objects'] else SWIFT_SCALARS[item]}]"
    elif t == "map":
        base = f"[String: {SWIFT_SCALARS[f['value']]}]"
    else:
        base = SWIFT_SCALARS[t]
    return base + ("?" if f.get("nullable") else "")


def swift_struct(s: dict, name: str, fs: list[dict], indent: str) -> str:
    i1 = indent + "    "
    i2 = i1 + "    "
    props = []
    for f in fs:
        d = description(s, f)
        if d:
            props.append(f"{i1}/// {d}")
        props.append(f"{i1}public let {camel(f['name'])}: {swift_type(s, f)}")
    keys = []
    for f in fs:
        c = camel(f["name"])
        keys.append(f"{i2}case {c}" if c == f["name"] else f'{i2}case {c} = "{f["name"]}"')
    params = []
    for f in fs:
        default = " = nil" if f.get("nullable") else ""
        params.append(f"{i2}{camel(f['name'])}: {swift_type(s, f)}{default}")
    assigns = [f"{i2}self.{camel(f['name'])} = {camel(f['name'])}" for f in fs]
    return (
        f"{indent}public struct {name}: Codable, Sendable, Equatable {{\n"
        + "\n".join(props)
        + "\n\n"
        + f"{i1}enum CodingKeys: String, CodingKey {{\n"
        + "\n".join(keys)
        + f"\n{i1}}}\n\n"
        + f"{i1}public init(\n"
        + ",\n".join(params)
        + f"\n{i1}) {{\n"
        + "\n".join(assigns)
        + f"\n{i1}}}\n"
        + f"{indent}}}"
    )


def gen_swift(s: dict) -> str:
    enums = []
    for name, values in s["enums"].items():
        cases = []
        for v in values:
            c = camel(v)
            cases.append(f"        case {swift_ident(c)}" + ("" if c == v else f' = "{v}"'))
        enums.append(
            f"    public enum {pascal(name)}: String, CaseIterable, Codable, Sendable {{\n"
            + "\n".join(cases)
            + "\n    }"
        )
    objects = [swift_struct(s, name, fs, "    ") for name, fs in s["objects"].items()]
    top = swift_struct(s, TOP, s["fields"], "")
    # Splice the nested declarations in after the opening brace of the top-level struct.
    first_nl = top.index("\n")
    nested = "\n\n".join(enums + objects)
    top = top[:first_nl] + "\n" + nested + "\n" + top[first_nl:]

    max_lengths = "\n".join(f'        "{k}": {v},' for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f'        "{k}": {json.dumps(v)},' for k, v in s["enums"].items())

    return f"""{SWIFT_BANNER}

import Foundation

/// A model-written reading of one session: what got built, how the person built it,
/// and how they steered the agent. Produced on the user's machine by their own
/// `claude -p` from a digest of the transcript, against analysis/schema.json.
///
/// Every string is bounded (`AnalysisSpec.maxLengths`), every score carries a
/// rationale, `confidence` is required, and a field the model could not ground in the
/// digest is nil or empty — never guessed. Deterministic stats (lines, prompts, tools,
/// tokens) are NOT here: they come from the engine and cannot be hallucinated.
///
/// Decode with a `JSONDecoder` whose `dateDecodingStrategy` is `.iso8601`;
/// `generated_at` is an ISO 8601 string on the wire.
{top}

public enum AnalysisSpec {{
    public static let version = {s["version"]}

    /// Character caps by size class; the spec's `max` on a string field names one of these.
    public static let maxLengths: [String: Int] = [
{max_lengths}
    ]

    /// Legal values for every enum, in spec order, so a prompt retune that invents a
    /// value fails a test here rather than a 422 on the user's first sync.
    public static let enumValues: [String: [String]] = [
{enum_values}
    ]
}}
"""


# -------------------------------------------------------------------- typescript
def ts_type(s: dict, f: dict) -> str:
    t = f["type"]
    if t == "enum":
        base = pascal(f["values"])
    elif t == "object":
        base = f["item"]
    elif t == "list":
        item = f["item"]
        base = (item if item in s["objects"] else TS_SCALARS[item]) + "[]"
    elif t == "map":
        base = f"Partial<Record<{pascal(f['key'])}, {TS_SCALARS[f['value']]}>>"
    else:
        base = TS_SCALARS[t]
    return base + (" | null" if f.get("nullable") else "")


def ts_interface(s: dict, name: str, fs: list[dict]) -> str:
    lines = []
    for f in fs:
        d = description(s, f)
        if d:
            lines.append(f"  /** {d} */")
        opt = "?" if f.get("nullable") else ""
        lines.append(f"  {f['name']}{opt}: {ts_type(s, f)};")
    return f"export interface {name} {{\n" + "\n".join(lines) + "\n}"


def gen_ts(s: dict) -> str:
    unions = "\n".join(
        f"export type {pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in s["enums"].items()
    )
    enum_table = "\n".join(f"  {name}: {json.dumps(values)}," for name, values in s["enums"].items())
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    interfaces = "\n\n".join(
        [ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ts_interface(s, TOP, s["fields"])]
    )
    return f"""{TS_BANNER}

export const ANALYSIS_VERSION = {s["version"]};

/** Character caps by size class; string fields below name one of these in their doc. */
export const ANALYSIS_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{unions}

/** Legal values for every enum, in spec order — the same order Swift's CaseIterable uses. */
export const ANALYSIS_ENUMS = {{
{enum_table}
}} as const;

{interfaces}
"""


# ------------------------------------------------------------------------ python
def py_field(s: dict, f: dict) -> str:
    t = f["type"]
    kwargs: list[str] = []
    ml = max_len(s, f)
    if t == "enum":
        ann = "str"
    elif t == "object":
        ann = f["item"]
    elif t == "list":
        item = f["item"]
        if item in s["objects"]:
            inner = item
        elif item == "string" and ml is not None:
            inner = f"Annotated[str, Field(max_length={ml})]"
        else:
            inner = PY_SCALARS[item]
        ann = f"list[{inner}]"
        kwargs.append(f"max_length={f['max_items']}")
    elif t == "map":
        value = PY_SCALARS[f["value"]]
        if f["value"] == "double":
            value = "Annotated[float, Field(ge=0.0, le=1.0)]"
        ann = f"dict[str, {value}]"
    else:
        ann = PY_SCALARS[t]
        if t == "string" and ml is not None:
            kwargs.append(f"max_length={ml}")
        b = numeric_bounds(f)
        if b is not None:
            kwargs.append(f"ge={b[0]}")
            kwargs.append(f"le={b[1]}")
    if f.get("nullable"):
        ann += " | None"
        kwargs.insert(0, "default=None")
    if not kwargs:
        return f"    {f['name']}: {ann}"
    if kwargs == ["default=None"]:
        return f"    {f['name']}: {ann} = None"
    return f"    {f['name']}: {ann} = Field({', '.join(kwargs)})"


def py_model(s: dict, name: str, fs: list[dict]) -> str:
    body = "\n".join(py_field(s, f) for f in fs)
    out = f'class {name}(BaseModel):\n    model_config = ConfigDict(extra="forbid")\n\n{body}\n'
    enum_fields = [f["name"] for f in fs if f["type"] == "enum"]
    if enum_fields:
        names = ", ".join(json.dumps(n) for n in enum_fields)
        out += (
            "\n"
            f"    @field_validator({names})\n"
            "    @classmethod\n"
            "    def _validate_enum(cls, v, info):\n"
            "        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]\n"
            "        if v is not None and v not in allowed:\n"
            "            raise ValueError(\n"
            "                '%s=%r is not one of %r' % (info.field_name, v, allowed)\n"
            "            )\n"
            "        return v\n"
        )
    map_fields = [f["name"] for f in fs if f["type"] == "map"]
    if map_fields:
        names = ", ".join(json.dumps(n) for n in map_fields)
        out += (
            "\n"
            f"    @field_validator({names})\n"
            "    @classmethod\n"
            "    def _validate_map_keys(cls, v, info):\n"
            "        allowed = ANALYSIS_ENUM_VALUES[MAP_KEY_ENUMS[cls.__name__][info.field_name]]\n"
            "        bad = sorted(k for k in v if k not in allowed)\n"
            "        if bad:\n"
            "            raise ValueError(\n"
            "                '%s has keys %r not in %r' % (info.field_name, bad, allowed)\n"
            "            )\n"
            "        return v\n"
        )
    return out


def gen_py(s: dict) -> str:
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(
        f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items()
    )
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in all_fields(s)
    )
    map_key_enums = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["key"] for f in fs if f["type"] == "map"})
        + ","
        for owner, fs in all_fields(s)
        if any(f["type"] == "map" for f in fs)
    )
    models = "\n\n".join(py_model(s, name, fs) for name, fs in all_fields(s))
    return f'''{PY_BANNER}
"""A session analysis, server side. `extra="forbid"` plus the bounds below are the
enforcement half of analysis/schema.json: the constrained decoder that produced the
document honours enums and required fields, but string lengths and numeric ranges are
checked HERE, on the way into Postgres, or nowhere."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

ANALYSIS_VERSION = {s["version"]}

Sha256Hex = Annotated[str, Field(pattern=r"{SHA256_PATTERN}")]

#: Character caps by size class; the spec's `max` on a string field names one of these.
ANALYSIS_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in spec order.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}

#: model name -> map field name -> enum its keys must come from.
MAP_KEY_ENUMS: dict[str, dict[str, str]] = {{
{map_key_enums}
}}


{models}
'''


# ------------------------------------------------------------------- json schema
def json_prop(s: dict, f: dict) -> dict:
    t = f["type"]
    ml = max_len(s, f)
    if t == "enum":
        sch: dict = {"type": "string", "enum": list(s["enums"][f["values"]])}
    elif t == "object":
        sch = {"$ref": f"#/$defs/{f['item']}"}
    elif t == "list":
        item = f["item"]
        if item in s["objects"]:
            items: dict = {"$ref": f"#/$defs/{item}"}
        else:
            items = dict(JSON_SCALARS[item])
            if item == "string" and ml is not None:
                items["maxLength"] = ml
        sch = {"type": "array", "items": items, "maxItems": f["max_items"]}
        if f.get("min_items"):
            sch["minItems"] = f["min_items"]
    elif t == "map":
        # Keyed by an enum, so it is an object with one optional property per legal key.
        # `additionalProperties` must be exactly false for a constrained decoder, and an
        # unknown key is a rejection rather than a stored value nobody can chart.
        value = dict(JSON_SCALARS[f["value"]])
        if f["value"] == "double":
            value.update({"minimum": 0.0, "maximum": 1.0})
        sch = {
            "type": "object",
            "properties": {k: dict(value) for k in s["enums"][f["key"]]},
            "additionalProperties": False,
        }
    else:
        sch = dict(JSON_SCALARS[t])
        if t == "string" and ml is not None:
            sch["maxLength"] = ml
        b = numeric_bounds(f)
        if b is not None:
            sch["minimum"], sch["maximum"] = b
        if f["name"] == "analysis_version":
            # Doc: "== spec version". The one value the model must copy, not decide.
            sch["const"] = s["version"]
    if f.get("nullable"):
        sch = {"anyOf": [sch, {"type": "null"}]}
    d = description(s, f)
    return {"description": d, **sch} if d else sch


def json_object(s: dict, fs: list[dict]) -> dict:
    return {
        "type": "object",
        "properties": {f["name"]: json_prop(s, f) for f in fs},
        "required": [f["name"] for f in fs if not f.get("nullable")],
        "additionalProperties": False,
    }


def gen_schema(s: dict) -> str:
    top = json_object(s, s["fields"])
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "GENERATED by scripts/gen_analysis.py from spec/analysis.v1.json — DO NOT EDIT. "
            "Handed to `claude -p --json-schema`."
        ),
        "title": TOP,
        "description": (
            "A reading of one coding session: what got built, how the person built it, and "
            "how they steered the agent. Every string is bounded, every score has a one-line "
            "rationale, and confidence is required. A field that cannot be grounded in the "
            "digest is null or empty, never guessed. Do not restate deterministic stats "
            "(lines, prompts, tool counts, tokens); they are measured elsewhere."
        ),
        **top,
        "$defs": {name: json_object(s, fs) for name, fs in s["objects"].items()},
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    s = load()
    print("gen_analysis.py")
    write(
        ROOT / "Packages/BuilderKit/Sources/BuilderModel/Generated/AnalysisSpec.swift",
        gen_swift(s),
    )
    write(ROOT / "mobile/src/generated/analysis.ts", gen_ts(s))
    write(ROOT / "server/builder/analysis_spec.py", gen_py(s))
    schema = gen_schema(s)
    write(ROOT / "analysis/schema.json", schema)
    # The same bytes, shipped inside the Swift package as a Bundle.module resource so the
    # agent's `claude -p --json-schema` receives exactly what the Python runner does.
    # Generated here rather than copied by hand: a copy is a second definition.
    write(ROOT / "Packages/BuilderKit/Sources/BuilderAnalysis/Resources/analysis_schema.json", schema)


if __name__ == "__main__":
    main()
