#!/usr/bin/env python3
"""Generate the privacy contract into Swift, Python, TypeScript, JSON and prose.

privacy/upload-contract.json is the ONLY hand-edited definition of what may leave the
machine. Everything below is derived from it, committed, and checked by
`make gen && git diff --exit-code` in CI.

The structural guarantee is the SERIALIZER, not the test: BuilderSync's SessionUpload
encodes through the generated `UploadField` CodingKey enum with a hand-written
encode(to:), and there is no synthesized Codable anywhere in that target. A field that
is not in this file is unrepresentable on the wire.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "privacy" / "upload-contract.json"

SWIFT_BANNER = "// GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."
PY_BANNER = "# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."

SWIFT_TYPES = {
    "sha256hex": "String",
    "string": "String",
    "int": "Int",
    "bool": "Bool",
    "datetime": "Date",
    "enum": "String",
    "base64": "String",
    "marks": "[StripMarkWire]",
    "toolmap": "[String: Int]",
    "tokens": "TokenBucketsWire",
    "models": "[ModelShareWire]",
    "url": "String",
}
PY_TYPES = {
    "sha256hex": "Sha256Hex",
    "string": "str",
    "int": "int",
    "bool": "bool",
    "datetime": "datetime",
    "enum": "str",
    "base64": "str",
    "marks": "list[StripMarkWire]",
    "toolmap": "dict[str, int]",
    "tokens": "TokenBucketsWire",
    "models": "list[ModelShareWire]",
    "url": "str",
}
TS_TYPES = {
    "sha256hex": "string",
    "string": "string",
    "int": "number",
    "bool": "boolean",
    "datetime": "string",
    "enum": "string",
    "base64": "string",
    "marks": "StripMarkWire[]",
    "toolmap": "Record<string, number>",
    "tokens": "TokenBucketsWire",
    "models": "ModelShareWire[]",
    "url": "string",
}


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def fields(c: dict) -> list[dict]:
    return c["fields"]


# --------------------------------------------------------------------------- swift
def gen_swift(c: dict) -> str:
    fs = fields(c)
    cases = "\n".join(f'    case {f["name"]}' for f in fs)

    def mode_set(mode: str) -> str:
        names = [f'.{f["name"]}' for f in fs if mode in f["modes"]]
        return "[\n        " + ",\n        ".join(names) + ",\n    ]"

    enums = "\n".join(
        f'        "{f["name"]}": {json.dumps(sorted(f["values"]))},'
        for f in fs
        if f["type"] == "enum"
    )

    return f"""{SWIFT_BANNER}

import Foundation

/// Every key that may appear on the wire. `SessionUpload` encodes through this and only
/// this, with a hand-written `encode(to:)` and no synthesized `Codable`, so a field that
/// is not a case here is *unrepresentable* — adding a stored property to a model cannot
/// change the payload.
public enum UploadField: String, CodingKey, CaseIterable, Sendable {{
{cases}
}}

/// Per-repo visibility. `excluded` is deliberately not a mode: an excluded repo produces
/// zero uploads, and if ANY event in a session resolves to an excluded repo the entire
/// session is dropped rather than partially uploaded.
public enum PrivacyMode: String, Sendable, CaseIterable {{
    case publicRepo = "public"
    case anonymous

    public var allowedFields: Set<UploadField> {{
        switch self {{
        case .publicRepo: return UploadContract.publicFields
        case .anonymous:  return UploadContract.anonymousFields
        }}
    }}
}}

public enum UploadContract {{
    public static let version = {c["version"]}

    public static let publicFields: Set<UploadField> = {mode_set("public")}

    public static let anonymousFields: Set<UploadField> = {mode_set("anonymous")}

    /// Legal values for every enum-typed field, so a typo becomes a test failure here
    /// rather than a 422 from the server on the user's first sync.
    public static let enumValues: [String: [String]] = [
{enums}
    ]
}}

// MARK: - Wire value types

public struct StripMarkWire: Codable, Sendable, Equatable {{
    public let ms: Int
    public let k: Int
    public init(ms: Int, k: Int) {{ self.ms = ms; self.k = k }}
}}

/// Five separate buckets. There is no `total` — `cache_read` IS billed, at a reduced
/// rate, and on a cache-heavy agentic workload it dominates the input side, so a single
/// summed field would silently pick a definition.
public struct TokenBucketsWire: Codable, Sendable, Equatable {{
    public let input: Int
    public let output: Int
    public let cacheRead: Int
    public let cacheWrite5m: Int
    public let cacheWrite1h: Int

    enum CodingKeys: String, CodingKey {{
        case input, output
        case cacheRead = "cache_read"
        case cacheWrite5m = "cache_w5m"
        case cacheWrite1h = "cache_w1h"
    }}

    public init(input: Int, output: Int, cacheRead: Int, cacheWrite5m: Int, cacheWrite1h: Int) {{
        self.input = input; self.output = output; self.cacheRead = cacheRead
        self.cacheWrite5m = cacheWrite5m; self.cacheWrite1h = cacheWrite1h
    }}
}}

public struct ModelShareWire: Codable, Sendable, Equatable {{
    public let modelID: String
    public let outputTokenShare: Double

    enum CodingKeys: String, CodingKey {{
        case modelID = "model_id"
        case outputTokenShare = "output_token_share"
    }}

    public init(modelID: String, outputTokenShare: Double) {{
        self.modelID = modelID; self.outputTokenShare = outputTokenShare
    }}
}}
"""


# -------------------------------------------------------------------------- python
def gen_py(c: dict) -> str:
    fs = fields(c)
    lines = []
    for f in fs:
        t = PY_TYPES[f["type"]]
        if f.get("nullable"):
            lines.append(f'    {f["name"]}: {t} | None = None')
        else:
            lines.append(f'    {f["name"]}: {t}')
    body = "\n".join(lines)

    enum_fields = [f for f in fs if f["type"] == "enum"]
    enum_table = "\n".join(
        '    "%s": %s,' % (f["name"], json.dumps(sorted(f["values"]))) for f in enum_fields
    )
    enum_names = ", ".join('"%s"' % f["name"] for f in enum_fields)
    vtext = (
        f"    @field_validator({enum_names})\n"
        "    @classmethod\n"
        "    def _validate_enum(cls, v, info):\n"
        "        allowed = ENUM_VALUES.get(info.field_name)\n"
        "        if v is not None and allowed is not None and v not in allowed:\n"
        "            raise ValueError(\n"
        "                '%s=%r is not one of %r' % (info.field_name, v, allowed)\n"
        "            )\n"
        "        return v\n"
    )

    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]), indent=4)
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]), indent=4)

    return f'''{PY_BANNER}
"""The wire contract, server side. `extra="forbid"` is the belt-and-suspenders half of
the guarantee: even a hostile or stale client cannot push an undeclared field into
Postgres. The client-side half is that undeclared fields are unrepresentable at all."""

from __future__ import annotations

import re
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

CONTRACT_VERSION = {c["version"]}

_SHA256 = re.compile(r"^[0-9a-f]{{64}}$")
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{{64}}$")]

PUBLIC_FIELDS = {pub}

ANONYMOUS_FIELDS = {anon}

#: Legal values for every enum-typed field, so a client typo is a 422 with a useful
#: message rather than a constraint violation deep in a batch insert.
ENUM_VALUES: dict[str, list[str]] = {{
{enum_table}
}}


class StripMarkWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ms: int
    k: int


class TokenBucketsWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    input: int
    output: int
    cache_read: int
    cache_w5m: int
    cache_w1h: int


class ModelShareWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    model_id: str
    output_token_share: float


class SessionUpload(BaseModel):
    model_config = ConfigDict(extra="forbid")

{body}

{vtext}
'''


# ---------------------------------------------------------------------- typescript
def gen_ts(c: dict) -> str:
    fs = fields(c)
    lines = []
    for f in fs:
        t = TS_TYPES[f["type"]]
        opt = "?" if f.get("nullable") else ""
        doc = f'  /** {f["doc"]} */\n' if f.get("doc") else ""
        lines.append(f'{doc}  {f["name"]}{opt}: {t};')
    body = "\n".join(lines)
    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]))
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]))
    return f"""{SWIFT_BANNER.replace('Swift', 'TypeScript')}

export const CONTRACT_VERSION = {c["version"]};

export interface StripMarkWire {{ ms: number; k: number; }}
export interface TokenBucketsWire {{
  input: number; output: number;
  cache_read: number; cache_w5m: number; cache_w1h: number;
}}
export interface ModelShareWire {{ model_id: string; output_token_share: number; }}

/** The complete set of fields the phone can ever receive for a session. */
export interface SessionWire {{
{body}
}}

export const PUBLIC_FIELDS = {pub} as const;
export const ANONYMOUS_FIELDS = {anon} as const;
"""


# ------------------------------------------------------------------------- prose
def gen_privacy_md(c: dict) -> str:
    fs = fields(c)
    rows = []
    for f in fs:
        modes = "public + anonymous" if len(f["modes"]) == 2 else f'**{f["modes"][0]} repos only**'
        doc = f.get("doc", "")
        rows.append(f'| `{f["name"]}` | {f["type"]} | {modes} | {doc} |')
    table = "\n".join(rows)

    return f"""<!-- GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT. -->

# What Builder sends, and what it does not

Builder reads the logs your AI coding tools already write to your own disk. Almost all of
that never moves. This page is generated directly from the file that defines the network
payload, so it cannot drift from the code: if a field is not in this table, the app has no
way to represent it on the wire.

## Never leaves your machine

Your prompts. The model's replies. Its thinking. Anything you or the model typed into a
file. Diffs and patches. File contents. **File paths, and file names.** Directory names.
Commit messages. Commit SHAs. Branch names. Your working directory. Your git remote URL.
The names of repositories you have not marked public. MCP server names. Terminal commands
and their output. Environment variables. URLs fetched. Your hostname. Your IP.

Not redacted versions of these. Not excerpts. There is no code path that sends them.

## What does leave, if you sign in

Every field, in full. `{c["version"]}` is the contract version.

| Field | Type | Sent for | What it is |
|---|---|---|---|
{table}

## Per-repository control

Every repository is **anonymous** by default: its sessions sync as a shape and a set of
counts, with no name attached. You can set a repository to **public** — which adds only
`repo_name`, `title` and `title_source` — or to **excluded**, which sends nothing at all.
If a single session touched an excluded repository, the whole session is dropped rather
than partially uploaded.

Titles come from the title your coding tool **already wrote to your disk**. Builder does
not send your prompts to a model to generate one. There is no such endpoint.

## Check it yourself

Do not take the above on faith. The agent is open source and these commands run locally.

```bash
# 1. Print every byte the agent would send. Sends nothing.
builder sync --dry-run --print-payload | jq

# 2. Diff its actual keys against this page, in both directions.
builder sync --dry-run --print-payload \\
  | jq -r '[paths(scalars)] | .[] | join(".")' \\
  | sed 's/\\.[0-9][0-9]*\\./.[]./g' | sort -u > /tmp/actual
curl -s "$BUILDER_BASE_URL/upload-fields.json" | jq -r '.fields[]' | sort -u > /tmp/declared
diff /tmp/actual /tmp/declared && echo "MATCHES PUBLISHED CONTRACT"

# 3. Pick a phrase you typed to your agent today. Go looking for it.
builder sync --dry-run --print-payload | grep -i "that phrase"   # no output, exit 1

# 4. Trust none of the above. Builder does not certificate-pin, on purpose.
mitmproxy -p 8080 &
HTTPS_PROXY=http://127.0.0.1:8080 builder sync
```

## Repository hashing: the honest limit

Repositories are identified by an HMAC of the normalized git origin URL. The key is a
**global constant, identical for every user** — matching the same repository across two
machines requires both to derive the same hash. It ships inside an open-source binary and
is **not secret**.

The hash defeats casual exposure and makes a database dump unreadable. It does **not**
survive a dictionary attack against public repository names. If you need real secrecy, set
the repository to `excluded`: it is never hashed, never uploaded, and never parsed again.
Private set intersection is the correct fix and is not built.

## Permissions

Builder does not require Full Disk Access, Screen Recording, or Accessibility, and does not
ask for them. It reads `~/.claude`, `~/.codex`, `~/.cursor` and Cursor's application support
directory, none of which are protected by those permissions today. If a future macOS release
restricts one of them, Builder will tell you which one and why, and will keep working on the
others.
"""


def main() -> None:
    c = json.loads(SPEC.read_text())
    print("gen_contract.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderSync/Generated/UploadContract.swift", gen_swift(c))
    write(ROOT / "server/builder/contract.py", gen_py(c))
    write(ROOT / "mobile/src/generated/contract.ts", gen_ts(c))
    write(
        ROOT / "server/builder/static/upload-fields.json",
        json.dumps(
            {"version": c["version"], "fields": sorted(f["name"] for f in fields(c))},
            indent=2,
        )
        + "\n",
    )
    write(ROOT / "PRIVACY.md", gen_privacy_md(c))


if __name__ == "__main__":
    main()
