#!/usr/bin/env python3
"""Generate the synthetic Codex rollout fixture and the stats the loader must reproduce.

    spec/fixtures/codex/synthetic_session.jsonl
    spec/fixtures/codex/synthetic_session.expected.json

The rollout is SYNTHETIC: 40 lines in the shapes verified from the Codex source (see the
docstring of analysis/codex.py for the per-shape provenance), not a captured session. It
exercises every branch the loader has: legacy-mode `user_message` / `agent_message` events
alongside their `response_item` copies (which must dedupe), an `<environment_context>`
envelope on the response_item user channel (which must NOT become a prompt), `shell` and
`local_shell_call` commands with the legacy JSON-with-metadata output, `exec_command` with
the "Process exited with code N" header (one non-zero), two `apply_patch` custom tool calls
with small patches, increasing `token_count` totals, a `compacted` record, a second
`turn_context`, and a `turn_aborted` with reason `interrupted`.

The expected file is generated by the loader, so on its own it only guards against drift.
The hand-counted invariants that make it evidence live in analysis/tests/test_codex.py.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from analysis import codex, digest

OUT = ROOT / "spec" / "fixtures" / "codex"
CWD = "/Users/dev/proj"


def ts(sec: float) -> str:
    """Stamps in the recorder's exact `…T14:00:SS.mmmZ` form, spaced a few seconds apart."""
    whole = int(sec)
    ms = round((sec - whole) * 1000)
    m, s = divmod(whole, 60)
    return f"2025-11-03T14:{m:02d}:{s:02d}.{ms:03d}Z"


def line(sec: float, typ: str, payload: dict) -> dict:
    return {"timestamp": ts(sec), "type": typ, "payload": payload}


def event(sec: float, etype: str, **kw) -> dict:
    return line(sec, "event_msg", {"type": etype, **kw})


def item(sec: float, itype: str, **kw) -> dict:
    return line(sec, "response_item", {"type": itype, **kw})


def usage(inp, cached, out, reasoning) -> dict:
    return {
        "input_tokens": inp,
        "cached_input_tokens": cached,
        "cache_write_input_tokens": 0,
        "output_tokens": out,
        "reasoning_output_tokens": reasoning,
        "total_tokens": inp + out,
    }


def shell_out(text: str, code: int, secs: float) -> str:
    # ASSUMED legacy `shell` output form (see analysis/codex.py).
    return json.dumps({"output": text, "metadata": {"exit_code": code, "duration_seconds": secs}})


def exec_out(text: str, code: int, secs: float) -> str:
    # VERIFIED exec_command form: core/src/tools/context.rs `response_header`.
    return f"Wall time: {secs:.4f} seconds\nProcess exited with code {code}\nOutput:\n{text}"


PATCH_1 = (
    "*** Begin Patch\n"
    "*** Update File: scripts/deploy.sh\n"
    "@@\n"
    "-set -e\n"
    "+set -euo pipefail\n"
    "+DRY_RUN=0\n"
    '+if [ "${1:-}" = "--dry-run" ]; then DRY_RUN=1; fi\n'
    "*** End Patch"
)
PATCH_2 = (
    "*** Begin Patch\n"
    "*** Update File: tests/test_deploy.py\n"
    "@@\n"
    '-    assert run(["--dry-run"]) == 1\n'
    '+    assert run(["--dry-run"]) == 0\n'
    "*** End Patch"
)

PROMPT_1 = "Add a --dry-run flag to scripts/deploy.sh and make sure the tests still pass"
PROMPT_2 = "Great — commit it and push"
REPLY_1 = "I added the flag; running the tests now."
REPLY_2 = "Both tests pass. `scripts/deploy.sh` now accepts `--dry-run`."
REPLY_3 = "Committed as abc1234. Pushing."
ENVELOPE = (
    "<environment_context>\n"
    f"  <cwd>{CWD}</cwd>\n"
    "  <approval_policy>on-request</approval_policy>\n"
    "  <sandbox_mode>workspace-write</sandbox_mode>\n"
    "  <shell>zsh</shell>\n"
    "</environment_context>"
)


def rollout() -> list[dict]:
    tc = {
        "cwd": CWD,
        "approval_policy": "on-request",
        "sandbox_policy": {"type": "workspace-write", "network_access": False},
        "model": "gpt-5-codex",
        "effort": "medium",
        "summary": "auto",
    }
    L = [
        line(
            0,
            "session_meta",
            {
                "id": "0192f3a0-7f4e-7c1a-9b2d-3e4f5a6b7c8d",
                "timestamp": ts(0),
                "cwd": CWD,
                "originator": "codex_cli_rs",
                "cli_version": "0.55.0",
                "source": "cli",
                "model_provider": "openai",
                "history_mode": "legacy",
                "git": {"commit_hash": "9f8e7d6c", "branch": "main"},
            },
        ),
        line(0.010, "turn_context", tc),
        item(
            0.020,
            "message",
            role="developer",
            content=[
                {
                    "type": "input_text",
                    "text": "<permissions_instructions>…</permissions_instructions>",
                }
            ],
        ),
        item(0.021, "message", role="user", content=[{"type": "input_text", "text": ENVELOPE}]),
        event(1.000, "user_message", message=PROMPT_1),
        item(1.002, "message", role="user", content=[{"type": "input_text", "text": PROMPT_1}]),
        event(1.005, "task_started", turn_id="turn-1", model_context_window=272000),
        item(3.100, "reasoning", summary=[], encrypted_content="gAAAAAB…"),
        event(3.101, "agent_reasoning", text="**Listing the scripts directory**"),
        item(
            3.200,
            "function_call",
            name="shell",
            arguments=json.dumps({"command": ["bash", "-lc", "ls scripts"], "workdir": CWD}),
            call_id="call_1",
        ),
        item(
            3.400,
            "function_call_output",
            call_id="call_1",
            output=shell_out("deploy.sh\nrelease.py\n", 0, 0.02),
        ),
        item(
            5.000,
            "function_call",
            name="shell",
            arguments=json.dumps(
                {"command": ["bash", "-lc", "cat scripts/deploy.sh"], "workdir": CWD}
            ),
            call_id="call_2",
        ),
        item(
            5.100,
            "function_call_output",
            call_id="call_2",
            output=shell_out("#!/bin/bash\nset -e\n…", 0, 0.01),
        ),
        item(
            9.000,
            "custom_tool_call",
            name="apply_patch",
            input=PATCH_1,
            call_id="call_3",
            status="completed",
        ),
        item(
            9.200,
            "custom_tool_call_output",
            call_id="call_3",
            output="Success. Updated the following files:\nM scripts/deploy.sh\n",
        ),
        event(11.000, "agent_message", message=REPLY_1),
        item(
            11.001,
            "message",
            role="assistant",
            content=[{"type": "output_text", "text": REPLY_1}],
            phase="commentary",
        ),
        item(
            12.000,
            "function_call",
            name="exec_command",
            arguments=json.dumps(
                {"cmd": "pytest -q tests/test_deploy.py", "workdir": CWD, "yield_time_ms": 10000}
            ),
            call_id="call_4",
        ),
        item(
            14.500,
            "function_call_output",
            call_id="call_4",
            output=exec_out(
                "F.\nFAILED tests/test_deploy.py::test_dry_run - AssertionError: assert 1 == 0\n1 failed, 1 passed in 1.02s\n",
                1,
                1.2345,
            ),
        ),
        event(
            15.000,
            "token_count",
            info={
                "total_token_usage": usage(12000, 8000, 900, 300),
                "last_token_usage": usage(12000, 8000, 900, 300),
                "model_context_window": 272000,
            },
            rate_limits=None,
        ),
        item(
            18.000,
            "custom_tool_call",
            name="apply_patch",
            input=PATCH_2,
            call_id="call_5",
            status="completed",
        ),
        item(
            18.100,
            "custom_tool_call_output",
            call_id="call_5",
            output="Success. Updated the following files:\nM tests/test_deploy.py\n",
        ),
        item(
            19.000,
            "function_call",
            name="exec_command",
            arguments=json.dumps({"cmd": "pytest -q tests/test_deploy.py", "workdir": CWD}),
            call_id="call_6",
        ),
        item(
            20.400,
            "function_call_output",
            call_id="call_6",
            output=exec_out("..\n2 passed in 0.88s\n", 0, 0.9012),
        ),
        event(22.000, "agent_message", message=REPLY_2),
        item(
            22.001,
            "message",
            role="assistant",
            content=[{"type": "output_text", "text": REPLY_2}],
            phase="final_answer",
        ),
        event(
            22.100,
            "token_count",
            info={
                "total_token_usage": usage(26000, 20000, 1500, 500),
                "last_token_usage": usage(14000, 12000, 600, 200),
                "model_context_window": 272000,
            },
            rate_limits=None,
        ),
        event(22.200, "task_complete", turn_id="turn-1", last_agent_message=REPLY_2),
        # second turn, 90 s later
        event(112.000, "user_message", message=PROMPT_2),
        event(112.005, "task_started", turn_id="turn-2", model_context_window=272000),
        item(
            114.000,
            "local_shell_call",
            call_id="call_7",
            status="completed",
            action={
                "type": "exec",
                "command": ["git", "commit", "-am", "Add --dry-run to deploy.sh"],
            },
        ),
        item(
            114.300,
            "function_call_output",
            call_id="call_7",
            output=shell_out(
                "[main abc1234] Add --dry-run to deploy.sh\n 2 files changed, 4 insertions(+), 2 deletions(-)\n",
                0,
                0.11,
            ),
        ),
        line(
            115.000,
            "compacted",
            {"message": "Summary: added --dry-run flag, fixed test expectation, committed."},
        ),
        line(115.010, "turn_context", dict(tc, effort="high")),
        event(
            116.000,
            "token_count",
            info={
                "total_token_usage": usage(30000, 23000, 1800, 600),
                "last_token_usage": usage(4000, 3000, 300, 100),
                "model_context_window": 272000,
            },
            rate_limits=None,
        ),
        event(117.000, "agent_message", message=REPLY_3),
        item(
            117.001, "message", role="assistant", content=[{"type": "output_text", "text": REPLY_3}]
        ),
        item(
            118.000,
            "function_call",
            name="shell",
            arguments=json.dumps(
                {"command": ["bash", "-lc", "git push origin main"], "workdir": CWD}
            ),
            call_id="call_8",
        ),
        item(
            119.000,
            "web_search_call",
            status="completed",
            action={"type": "search", "query": "git push hangs"},
        ),
        event(121.000, "turn_aborted", turn_id="turn-2", reason="interrupted"),
    ]
    return L


def main() -> int:
    L = rollout()
    assert len(L) == 40, len(L)
    OUT.mkdir(parents=True, exist_ok=True)
    jsonl = OUT / "synthetic_session.jsonl"
    with jsonl.open("w") as f:
        for r in L:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    s = codex.scan(jsonl)
    events, derivation = codex._derive(s)
    expected = {
        "_generated_by": "scripts/gen_codex_fixture.py — do not hand-edit",
        "harness": digest.detect_harness(jsonl),
        "events": len(events),
        "stats": digest.stats(events),
        "usage": s.usage,
        "meta": {k: v for k, v in s.meta.items() if k != "path"},
        "diagnostics": dict(s.diagnostics, derivation=derivation),
    }
    (OUT / "synthetic_session.expected.json").write_text(
        json.dumps(expected, indent=1, ensure_ascii=False) + "\n"
    )
    print(f"wrote {jsonl} ({len(L)} lines) and expected stats ({len(events)} events)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
