#!/usr/bin/env python3
"""The inter-event gap distribution of a transcript corpus, and what the v3 tau fit says.

    scripts/measure_gap_distribution.py                      # ~/.claude/projects + real-sessions
    scripts/measure_gap_distribution.py --root DIR           # another Claude Code store
    scripts/measure_gap_distribution.py --extra DIR          # a tree of Codex/Gemini/Cline/
                                                             #   opencode/Aider transcripts
    scripts/measure_gap_distribution.py --synthetic spec/fixtures/boundaries
    make measure-gaps                                        # all of the above, read-only

Prints, per corpus:
  * the gap histogram on log10 seconds in 0.1-decade bins (text bars);
  * the two-component Gaussian-mixture fit on log gaps (scripts/measure_boundaries.fit_tau
    — the same EM the Swift `ThresholdFitter` reproduces), its two modes, the valley where
    the weighted densities cross, and whether the pool is bimodal by the v3 rule;
  * the fraction of gaps above the valley;
  * the session count at the fitted tau against the count at the 900 s fallback;
  * the presence-to-presence intervals that fell during autonomy (> tauAutonomousSec),
    which is the measurement `tauReturnSplitSec` (7200 s) is waiting for;
  * the local hour of every autonomous record and of every idle-gap start, which is the
    measurement the 04:00 `day_boundary` hour is waiting for.

Everything under `--synthetic` is labelled SYNTHETIC in the output: those transcripts were
generated by scripts/gen_boundary_fixtures.py to exercise the rules and say nothing about
how people work. Standard library only, like the reference it imports.
"""

from __future__ import annotations

import argparse
import datetime as dt
import importlib
import json
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import measure_boundaries as mb  # noqa: E402

from capture.discover import iter_root_transcripts  # noqa: E402

DEFAULT_ROOT = "~/.claude/projects"
#: Where a sibling session in this workspace leaves real transcripts from other harnesses.
DEFAULT_EXTRA = (
    "/tmp/claude-0/-home-user/11d3bf1b-56c5-5641-a1a9-08ce6f6cf763/scratchpad/real-sessions"
)
BIN = 0.1  # decades


# ------------------------------------------------------------------------- corpora


def claude_code_pools(root: pathlib.Path) -> tuple[dict[str, list[dict]], int]:
    """Root transcripts only (capture's allowlist), keyed by project dir, folded by
    session lineage exactly as the reference does. Returns (pools, files)."""
    transcripts = iter_root_transcripts(root)
    keyed = []
    for t in transcripts:
        keyed.extend((t.project_dir, r) for r in mb.load_records(t.path))
    return mb.fold_by_session_lineage(keyed), len(transcripts)


#: Other harnesses: how to find their transcripts under a tree, and which loader in
#: `analysis/` reads one into timestamped digest events. Each loader is imported lazily
#: and any failure is reported, never raised — a probe that dies on one harness says
#: nothing about the others.
OTHER_HARNESSES = {
    "codex": ("analysis.codex", ["**/sessions/**/rollout-*.jsonl"]),
    "gemini": ("analysis.gemini", ["**/tmp/**/chats/*.json", "**/chats/session-*.json"]),
    "cline": ("analysis.cline", ["**/tasks/*/ui_messages.json"]),
    "opencode": ("analysis.opencode", ["**/opencode.db"]),
    "aider": ("analysis.aider", ["**/.aider.chat.history.md"]),
}


def other_pools(extra: pathlib.Path) -> tuple[dict[str, list[dict]], list[str]]:
    """One pool per transcript for every other harness found under `extra`. Events, not
    records: these loaders emit digest events, one per prompt/turn/tool call, which is a
    finer grain than a Claude Code record and is labelled as such in the output."""
    pools: dict[str, list[dict]] = {}
    notes: list[str] = []
    for harness, (module, patterns) in OTHER_HARNESSES.items():
        paths: list[pathlib.Path] = []
        for pat in patterns:
            paths.extend(p for p in extra.glob(pat) if p.is_file())
        if not paths:
            notes.append(f"{harness}: no transcripts under {extra}")
            continue
        try:
            loader = importlib.import_module(module)
        except Exception as e:  # noqa: BLE001 — report, do not die
            notes.append(f"{harness}: loader import failed ({e})")
            continue
        n_ok = 0
        for p in sorted(paths):
            try:
                events = loader.load_events(p)
            except Exception as e:  # noqa: BLE001
                notes.append(f"{harness}: {p.name}: {e}")
                continue
            recs = [
                {
                    "ts": e.ts,
                    "kind": e.kind,
                    "presence": e.kind in ("prompt", "interrupt", "human_edit"),
                    "cwd": None,
                    "sid": p.stem,
                }
                for e in events
                if e.ts
            ]
            if recs:
                pools[f"{harness}|{p.name}"] = recs
                n_ok += 1
        notes.append(f"{harness}: {n_ok} transcript(s), {sum(len(v) for k, v in pools.items() if k.startswith(harness + '|'))} events")
    return pools, notes


def synthetic_pools(fixtures: pathlib.Path) -> dict[str, list[dict]]:
    """spec/fixtures/boundaries/*.jsonl, one pool per file (as the generator cuts them)."""
    out: dict[str, list[dict]] = {}
    for p in sorted(fixtures.glob("*.jsonl")):
        out[p.stem] = mb.load_records(p)
    return out


# --------------------------------------------------------------------------- report


def histogram(log_gaps: list[float]) -> list[tuple[float, int]]:
    if not log_gaps:
        return []
    lo = math.floor(min(log_gaps) / BIN)
    hi = math.floor(max(log_gaps) / BIN)
    counts = [0] * (hi - lo + 1)
    for x in log_gaps:
        counts[math.floor(x / BIN) - lo] += 1
    return [((lo + i) * BIN, c) for i, c in enumerate(counts)]


def render_histogram(bins: list[tuple[float, int]], valley: float | None, width: int = 50) -> str:
    if not bins:
        return "  (no gaps)"
    peak = max(c for _, c in bins) or 1
    lines = []
    for edge, c in bins:
        bar = "#" * int(round(width * c / peak))
        mark = " <- valley" if valley is not None and edge <= valley < edge + BIN else ""
        lines.append(f"  {edge:5.1f} {10 ** edge:9.1f}s {c:7d} {bar}{mark}")
    return "\n".join(lines)


def presence_during_autonomy(pools: dict[str, list[dict]], tau: float) -> list[float]:
    """Presence-to-presence intervals inside continuous activity that exceed
    tauAutonomousSec — the human went quiet long enough for the agent to be on its own,
    and then came back without an idle gap in between. Rule `human_returned` fires on the
    ones over tauReturnSplitSec; this is the distribution that decides where that line is."""
    out = []
    for recs in pools.values():
        out.extend(x for x in mb.presence_intervals(recs, tau) if x > mb.TAU_AUTONOMOUS)
    return out


def hour_histograms(pools: dict[str, list[dict]], tz: dt.tzinfo, tau: float) -> tuple[list[int], list[int]]:
    """(local hour of every autonomous record, local hour of every idle-gap start)."""
    auto = [0] * 24
    idle = [0] * 24
    for recs in pools.values():
        rs = sorted(recs, key=lambda r: r["ts"])
        last_p = None
        for i, r in enumerate(rs):
            if i:
                gap = r["ts"] - rs[i - 1]["ts"]
                if gap > tau:
                    idle[dt.datetime.fromtimestamp(rs[i - 1]["ts"], tz).hour] += 1
                    last_p = None
                since = None if last_p is None else rs[i - 1]["ts"] - last_p
                if since is None or since > mb.TAU_AUTONOMOUS:
                    auto[dt.datetime.fromtimestamp(r["ts"], tz).hour] += 1
            if r["presence"]:
                last_p = r["ts"]
    return auto, idle


def analyse(label: str, pools: dict[str, list[dict]], tz: dt.tzinfo, synthetic: bool) -> dict:
    gaps: list[float] = []
    zero = 0
    for recs in pools.values():
        ts = sorted(r["ts"] for r in recs)
        for i in range(1, len(ts)):
            g = ts[i] - ts[i - 1]
            if g > 0:
                gaps.append(g)
            else:
                zero += 1
    # Two fits. The first is the naive Halfaker fit on RECORD gaps — reported because it is
    # what one would try first, and because on real data it finds the harness's write
    # cadence, not the human. The second is the v3 fit on human-act intervals, which is
    # the one the sessionizer uses.
    record_fit = mb.fit_tau(gaps)
    pgaps: list[float] = []
    for recs in pools.values():
        pgaps.extend(mb.presence_gaps(recs))
    fit = mb.fit_tau(pgaps)
    log_gaps = [math.log10(g) for g in gaps]
    log_pgaps = [math.log10(g) for g in pgaps]
    above = sum(1 for x in log_pgaps if fit.valley is not None and x > fit.valley)
    above_records = sum(1 for x in log_gaps if record_fit.valley is not None and x > record_fit.valley)
    cut_fit = mb.sessionize_pools(pools, tz, tau=fit.tau)
    cut_900 = mb.sessionize_pools(pools, tz, tau=mb.TAU_SESSION_FALLBACK)
    by_reason = {k: 0 for k in mb.END_REASONS}
    for cut in cut_fit.values():
        for s in cut:
            by_reason[s["end_reason"]] += 1
    pia = presence_during_autonomy(pools, fit.tau)
    auto_h, idle_h = hour_histograms(pools, tz, fit.tau)
    return {
        "label": label,
        "synthetic": synthetic,
        "pools": len(pools),
        "records": sum(len(v) for v in pools.values()),
        "gaps": len(gaps),
        "zero_gaps_excluded": zero,
        "percentiles_s": {q: mb.pct(gaps, q / 100) for q in (50, 90, 98, 99, 99.9)},
        "histogram": histogram(log_gaps),
        "record_gap_fit": record_fit.as_dict(),
        "fraction_of_record_gaps_above_its_valley": (
            (above_records / len(gaps)) if gaps and record_fit.valley is not None else None
        ),
        "presence_intervals": len(pgaps),
        "presence_histogram": histogram(log_pgaps),
        "fit": fit.as_dict(),
        "fraction_above_valley": (above / len(pgaps)) if pgaps and fit.valley is not None else None,
        "sessions_at_fitted_tau": sum(len(c) for c in cut_fit.values()),
        "sessions_at_900": sum(len(c) for c in cut_900.values()),
        "end_reasons_at_fitted_tau": by_reason,
        "presence_intervals_during_autonomy_s": {
            "n": len(pia),
            "p50": mb.pct(pia, 0.5),
            "max": max(pia) if pia else None,
            "bands": {
                "30m-1h": sum(1 for x in pia if x < 3600),
                "1h-2h": sum(1 for x in pia if 3600 <= x < 7200),
                "2h-4h": sum(1 for x in pia if 7200 <= x < 14400),
                ">=4h": sum(1 for x in pia if x >= 14400),
            },
        },
        "autonomous_records_by_local_hour": auto_h,
        "idle_gap_starts_by_local_hour": idle_h,
    }


def print_report(r: dict) -> None:
    tag = "SYNTHETIC — generated fixtures, not evidence" if r["synthetic"] else "REAL"
    print(f"\n=== {r['label']}  [{tag}]")
    print(
        f"pools {r['pools']}  records/events {r['records']:,}  gaps {r['gaps']:,} "
        f"(+{r['zero_gaps_excluded']} zero-length excluded)"
    )
    pc = r["percentiles_s"]
    print(
        "gap percentiles: "
        + "  ".join(f"p{q:g} {v:.1f}s" for q, v in pc.items())
    )
    rf = r["record_gap_fit"]
    print("histogram of log10(RECORD gap seconds), 0.1-decade bins:")
    print(render_histogram(r["histogram"], rf["valley"]))
    print("naive fit on record gaps (NOT what v3 uses): " + mb.describe_fit(mb.TauFit(**rf), "record gaps"))
    if r["fraction_of_record_gaps_above_its_valley"] is not None:
        print(f"  fraction of record gaps above that valley: {r['fraction_of_record_gaps_above_its_valley']:.4f}")
    fit = r["fit"]
    print(f"histogram of log10(HUMAN presence-to-presence interval seconds), n={r['presence_intervals']}:")
    print(render_histogram(r["presence_histogram"], fit["valley"]))
    print("v3 fit on presence intervals (what the sessionizer uses): " + mb.describe_fit(mb.TauFit(**fit)))
    if r["fraction_above_valley"] is not None:
        print(f"  fraction of presence intervals above the valley: {r['fraction_above_valley']:.4f}")
    print(
        f"sessions at fitted tau {fit['tau']:.0f} s: {r['sessions_at_fitted_tau']}   "
        f"at 900 s fallback: {r['sessions_at_900']}   end reasons at fitted: {r['end_reasons_at_fitted_tau']}"
    )
    p = r["presence_intervals_during_autonomy_s"]
    print(
        f"presence→presence intervals that crossed tauAutonomous (30 m) without an idle gap: "
        f"n {p['n']}  p50 {mb.fmt(p['p50']) if p['n'] else '-'}  max {mb.fmt(p['max']) if p['n'] else '-'}  bands {p['bands']}"
    )
    print(
        "autonomous records by local hour: "
        + " ".join(f"{h:02d}:{n}" for h, n in enumerate(r["autonomous_records_by_local_hour"]) if n)
    )
    print(
        "idle-gap starts by local hour:    "
        + " ".join(f"{h:02d}:{n}" for h, n in enumerate(r["idle_gap_starts_by_local_hour"]) if n)
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=DEFAULT_ROOT, help="Claude Code transcript store")
    ap.add_argument("--extra", default=DEFAULT_EXTRA, help="tree holding other harnesses' transcripts")
    ap.add_argument("--synthetic", default=None, help="a fixture dir to analyse, labelled SYNTHETIC")
    ap.add_argument("--tz", default=None, help="IANA zone; default: system local")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    tz = dt.datetime.now().astimezone().tzinfo
    if a.tz:
        import zoneinfo

        tz = zoneinfo.ZoneInfo(a.tz)

    reports = []
    notes: list[str] = []
    root = pathlib.Path(a.root).expanduser()
    cc, n_files = claude_code_pools(root)
    notes.append(f"claude_code: {n_files} root transcript(s) under {root}")
    if cc:
        reports.append(analyse(f"Claude Code root transcripts under {root}", cc, tz, False))
    extra = pathlib.Path(a.extra).expanduser() if a.extra else None
    other: dict[str, list[dict]] = {}
    if extra and extra.is_dir():
        other, more = other_pools(extra)
        notes.extend(more)
        if other:
            reports.append(analyse(f"other harnesses under {extra} (digest events)", other, tz, False))
    else:
        notes.append(f"no other-harness tree at {extra}")
    if cc and other:
        merged = dict(cc)
        merged.update(other)
        reports.append(analyse("every real pool together (what the v3 fit sees)", merged, tz, False))
    if a.synthetic:
        syn = synthetic_pools(pathlib.Path(a.synthetic))
        if syn:
            reports.append(analyse(f"fixtures under {a.synthetic}", syn, tz, True))

    if a.json:
        json.dump({"notes": notes, "reports": reports}, sys.stdout, indent=1, default=str)
        return 0
    for n in notes:
        print("note:", n)
    for r in reports:
        print_report(r)
    if not reports:
        print("nothing to measure")
    return 0


if __name__ == "__main__":
    sys.exit(main())
